### ISSUE TITLE
Decklist appearing

### ISSUE THREAD

**Issue by waitthisisntmtg** [extesy/DeckTracker#1]
Hey Ex,

I was trying this out a bit and works great usually but there were two issues with the decklist showing in game. One is that It sometimes didn't seem to have the space to show the whole list, it would usually be cutting off a couple of the last sigils. Could probably solve easily by making it an adjustable size on screen maybe?

Also, randomly it seems, it won't know my whole deck. For example my last two games, the first one it grabbed the deck no problem, next game it only showed me the cards I had already pulled. Let me know if you need anything from me!

**Comment by extesy** [comment]
@waitthisisntmtg Thanks for testing.

1. It is supposed to scale the deck size when it doesn't fit on the screen. Not sure why it's not working, I'll check.
2. Do you remember if this happened in version 1.0.2 or 1.0.3? Does it happen every time or randomly?

**Comment by extesy** [comment]
@waitthisisntmtg please upgrade to the latest version (1.0.5 at the moment) and let me know if you still can reproduce. For the scaling bug please take a full-screen screenshot in case if you run Eternal in a window.

**Comment by waitthisisntmtg** [comment]
Hey Extesy,

It appears that it happens after a mulligan. Here is a screenshot. It appeared perfectly prior to the mulligan, but it then resized like this:

![image](https://cloud.githubusercontent.com/assets/28144402/25577663/f0574292-2e35-11e7-822e-020715b6b4bb.png)

**Comment by waitthisisntmtg** [comment]
And here it is not reading the whole deck, only my hand:

![image](https://cloud.githubusercontent.com/assets/28144402/25577710/80aabb62-2e36-11e7-9945-48a851dd9f02.png)

**Comment by extesy** [comment]
@waitthisisntmtg Thanks for the screenshots, they are very helpful. What game mode is on the second screenshot? Is it Gauntlet or Forge?

**Comment by waitthisisntmtg** [comment]
Hey ex, 

They are both Gauntlet. 

Thanks!

**Comment by extesy** [comment]
@waitthisisntmtg I have fixed the Forge mode but I can't reproduce the full deck not showing in the Gauntlet mode. I need to know more details the would help me reproduce and identify the problem.

**Comment by waitthisisntmtg** [comment]
Okay, what would be helpful? Lemme know I'll send it your way.

**Comment by extesy** [comment]
@waitthisisntmtg I need to identify the difference between the game with this issue and the game without this issue. Several questions:
1. Does this issue happen truly randomly, like one Gauntlet game the deck is not pulled and the next Gauntlet game it is working again? Is there any pattern to it?
2. Are you doing anything special just before the issue happens? Like restarting the game or editing deck or anything that you are not doing before the normal game when the issue doesn't happen?
3. If you have difficulty answering the previous two questions then I will need logs, see [Reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section.

**Comment by waitthisisntmtg** [comment]
I'll have to test it a bit more to see. Sometimes it fixes when I change decks or enter the editor, other times it doesn't. 

Oh also I'm pretty sure it doesn't work if you start eternal prior to starting the tracker. Seems to cause a bit of a freak out for the tracker. 

Thanks! 
Ethan

**Comment by waitthisisntmtg** [comment]
Did a little testing with the newest version you put out and now it is appearing perfectly!
