### ISSUE TITLE
New deck achetypes for Eternal

### ISSUE THREAD

**Issue by AustinYQM** [extesy/DeckTracker#10]
Here are some you can add for eternal.

Crown of Possibilities : Crown of Possibilities
Clockroach : Crown of Possibilities
Nesting Aviator: Crown of Possibilities

Icaria, the Liberator : Armory
Starsteel Diasho : Armory

Haunting Scream + Gorgon Fanatic : Scream

**Comment by extesy** [comment]
Note to self: load `decktypes.txt` file if it exists in the deck tracker's app folder.

**Comment by extesy** [comment]
I've applied your PR #11 in release 1.0.28 and also added ability to override embedded `decktypes.txt` file with a custom one if you place it in the app folder. Please experiment and let me know what you think.

**Comment by AustinYQM** [comment]
Awesome. I understand the changes you made to my commit and I will use that information going forward. Having the ability to use a custom decktype.txt will help me test stuff as I add them (though I'll have to hope I go against the deck to test it lol). 

Could to explain how ContainsAny works? As well as Contains. I mean I get the idea but what is the number before the cards?

**Comment by extesy** [comment]
`Contains` means the deck must contain all cards from the parameters list. `ContainsAny` means that the deck must contain _any N_ cards from the list. Like any 3 out of 4, for example.
