### ISSUE TITLE
Overlay minimized, can't recover

### ISSUE THREAD

**Issue by BDubbB** [extesy/DeckTracker#101]
Hi,

I have a problem and a few suggestions.

First, let me say, this has happened before, and uninstalling/reinstalling doesn't fix the issue. The in-game overlay was minimized by dragging a card from the hand all the way to the side of the screen where the overlay was (somehow this resizes the overlay). I tried using all the F-Key functions to restore it; I also tried clicking and dragging from the spot on the screen where I can see a little grey square. Neither of those options worked.

I tried uninstalling and reinstalling. That doesn't work. Finally, I uninstalled, then manually deleted the files stored in Appdata/Local and Appdata/roaming, then reinstalled. This cleared the configuration, I'm guessing (so I probably only needed to delete the config file), which finally restored the overlay. However, only a few days later, it has happened again.

I would suggest that there be a button to lock the overlay after you have it the way you want it. Also, there should be an easy way to restore minimized overlay. Finally, I think that the overlay shouldn't be able to be downsized without clicking directly on it first.

Thanks for your time. Oh! Thanks for the great tracker too!

Edit:

I opened "C:\Users\(USERNAME)\AppData\Roaming\UniversalDeckTracker\config.json" in an online .json editor, changed ""playerDeckScale": -0.019xxxxxx," back to ""playerDeckScale": 1,", renamed the old config.json to config.json.bak, saved the new file as config.json in the same directory, and BOOM! It worked. Everything is back to normal. A button to simply set the deck scales back to "1" in the .json would do it, I think. Also, I think it would still be a good idea to have a "Lock Overylay" button, a "Reset Overlay Scale" button, and make the overlay unable to be scaled without clicking directly on the overly first (before dragging).

**Comment by extesy** [comment]
I have added a protection about this edge case in `1.0.60`.
