### ISSUE TITLE
How do you delete the game info saved so i will have no stats?

### ISSUE THREAD

**Issue by mrworld86** [extesy/DeckTracker#103]
How do you delete the game info saved so i will have no stats?

Thanks, 
Jeff

**Comment by extesy** [comment]
@mrworld86 you can right click on your decks in the left list and delete them. Or you can also delete `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\games.log` file.

**Comment by extesy** [comment]
@mrworld86 did you really ask that so that you can tell it to CVH on stream? :)
