### ISSUE TITLE
Feature Request: Percentage to draw given card next

### ISSUE THREAD

**Issue by NoahC92** [extesy/DeckTracker#105]
A small percentage next to each card (possibly next to the number of X card left in deck) that shows the statistical probability of drawing that card next. For example, in this screenshot I have 4 Seek Power in 68 cards. This is a 5.8% chance of drawing Seek Power as my next card. Eilyn's Choice would be 1.4% and so on.
![screenshot_6](https://user-images.githubusercontent.com/30736018/28986598-7f7aa064-791c-11e7-9644-ad31e6b3d5be.png)

**Comment by extesy** [comment]
Why do you need exact absolute probability? By having card counts you can immediately see relative probability which is the same for all cards with the same count. And there are only 4 different options available.

If you have a 4 of each card in deck, how does it matter if each card has probability 5.3% if the only thing you actually need to know that it's the same chance for every card? This is just adding information noise without providing any new information.

**Comment by VitaliyKulikov** [comment]
additional useful information can be percentage of next draw by drops. two higher percentages, ex.: (3) - 40%, (4) - 20%

**Comment by extesy** [comment]
And how is that useful? So you would know that there's a 40% chance that you would draw any of 10 cards, and 20% for other 10 cards. How is that more helpful in any ways? Why couldn't you tell that already from card counts which show 4 for first set and 2 for the second set?

**Comment by VitaliyKulikov** [comment]
@extesy it's useful for combo-decks (0-costs decks, Journey to Sov, etc) with dynamic deck list #111.

`btw`: i don't understand why are you hiding  `DeckTracker.InGame.dll` code. in case, you are worry about  code-steal -> put licence and me (i think others) can develop `wontfix` (others) features. such, can be enabled/disabled in settings. a lot of people found some features for them and others useful in their gameplay.

**Comment by extesy** [comment]
@VitaliyKulikov Any project needs a direction in order to successfully develop into a cohesive product. Allowing anyone to add various random features without thinking about how they are linked to existing or future functionality won't end well and will result in a mess that's very hard to use by everybody.

Using a sample of 1-5 people requesting a feature for a product used by thousands and making claims about "a lot of people" is overgeneralizing.
