### ISSUE TITLE
Not showing own decklist in new Eternal event

### ISSUE THREAD

**Issue by emerald000** [extesy/DeckTracker#108]
On v1.0.66, your complete decklist isn't shown on the newest event currently going on in Eternal.

Only cards you draw appear in the list, similar to your opponent's list.

**Comment by extesy** [comment]
@emerald000 I'm short on gold at the moment. Can you please use a debug mode (https://github.com/extesy/DeckTracker#reporting-problems) and send me both `events.log` and `replays.log` files?

**Comment by SithLordOfSnark** [comment]
Usually when this happens, I simply reboot the deck tracker and then when I enter the next battle, it shows up properly.

**Comment by emerald000** [comment]
Here's the steps of what I did in debug mode:

1. Loaded the tracker.
2. Loaded Eternal.
3. Played an Event game, where the tracker was exhibiting the same problems.
4. Played a Ranked game, where everything was fine.
5. Closed Eternal.
6. Closed the tracker.

[Here are the logs.](https://github.com/extesy/DeckTracker/files/1203372/logs.zip)

**Comment by extesy** [comment]
@emerald000 Thank you, try `1.0.67` release. I think it should be fixed now.
