### ISSUE TITLE
Showing UUID instead of card name during TESL tutorial

### ISSUE THREAD

**Issue by emerald000** [extesy/DeckTracker#109]
On v1.0.66. I booted up the game for the first time. Both decklists show up a bunch of UUIDs.

I know nothing about the game, but this sounds wrong.

![capture](https://user-images.githubusercontent.com/4655664/29000421-0ebdbede-7a38-11e7-8fcf-f883b2112112.PNG)

**Comment by extesy** [comment]
@emerald000 try restarting the game
