### ISSUE TITLE
Error log on Installation

### ISSUE THREAD

**Issue by Mchieal** [extesy/DeckTracker#112]
I tried to open UniversalDeckTracker.exe(install), and when I press run, I get a popup that says:

Installation has failed

There was an error while installing the application.
Check the setup log for more information and contact
the author.

[SquirrelSetup.zip](https://github.com/extesy/DeckTracker/files/1203429/SquirrelSetup.zip)

**Comment by extesy** [comment]
@Mchieal Your log is from installing Discord, not Deck Tracker.

**Comment by Mchieal** [comment]
That is the log that opens up when I press "Open Setup Log" after trying to
run UniversalDeckTracker.exe

I was confused when the log said all the stuff about discord. That makes
more sense, though I don't understand why this log is opened from a failed
install of UniversalDeckTracker.exe


I could use OBS to get a snapshot video of what happens when I try to
install?

-Michael

**Comment by extesy** [comment]
@Mchieal It's something very specific to your machine. Probably an antivirus or user permissions or some other software. I'm afraid I won't be able to provide tech support for that.

**Comment by Mchieal** [comment]
Alright, thank you.

**Comment by LycaNinja** [comment]
If this is still an issue for anyone, I had this issue and fixed it:

Go to C:\Users\(Username)\AppData\Local\ and delete the UniversalDeckTracker folder, close any of the games that would use it, and reinstall.
