### ISSUE TITLE
UDT crashes while game is running

### ISSUE THREAD

**Issue by wispydanish** [extesy/DeckTracker#117]
Whenever I install and run the application while the game is running I get an immediate crash. If the game is not running, it opens, but crashes again when starting the game. 
Screenshot of the app running without ESL running: 
![udt bug 1](https://user-images.githubusercontent.com/30783109/29146797-0ef56f5e-7d18-11e7-9deb-5fafb8033f27.png)

Screenshot of the crash once ESL is running:

![udt bug 2](https://user-images.githubusercontent.com/30783109/29146804-1aefd6d2-7d18-11e7-98b4-e4462912e5e2.png)

My steps to reproduce (although I'm sure it's some conflict on my system and won't be reproducible):

1. Download exe of UDT from github
2. Run installer (I've run and installed as an administrator and not as an administrator)
3. Run UDT

If there are any known conflicts with other programs perhaps that will help. Any help is appreciated.

**Comment by extesy** [comment]
@wispydanish Please install https://www.microsoft.com/en-us/download/details.aspx?id=50040 and let me know if that solves the problem.

**Comment by wispydanish** [comment]
Hello,

I installed from the provided link and restarted my system. Went and uninstalled UDT, reinstalled it, but am still facing the same problem.

**Comment by wispydanish** [comment]
Any other possible solutions for this problem? 

Thank you.

**Comment by extesy** [comment]
Not yet. I'll add some debug info to help with tracking down the potential problem in the new build.

**Comment by BlackDogXX** [comment]
Hello,

I have the same problem and the solution i've found to fix it is to close steam and start tracker and game. Steam restarts after game launching and the tracker works fine.

I've also tried without the steam overlay, but tracker always crashes at launching.

I hope i've been usefull.

++

**Comment by wispydanish** [comment]
Thank you @extesy for the help.

@BlackDogXX I will try this out. When you say start tracker and game, do you mean run the game independently of Steam?? Or relaunch Steam, then ESL?

**Comment by BlackDogXX** [comment]
I close steam and I run the game in the steam folder. Before I have started the tracker. 

When I launch the game with the TES legends exe (tracker is already started),   steam restart automatically.

**Comment by wispydanish** [comment]
Followed the steps from @BlackDogXX but the tracker still crashes.

1, Closed out Steam completely.
2. Opened the tracker
3. Ran ESL from the steam folder
4. Game started, then Steam auto started
5. Tracker crashed

Thanks anyway @BlackDogXX , really appreciate your help.

**Comment by BlackDogXX** [comment]
I'm sorry that it doesn't work for you. 

You can also try to download the bethesda launcher to see if it run totally without steam. 

With it, you will be able to see if the problem come from steam or not. 

If not, the problem may come from an other program. I see on your sreenshot some programs like GOG launcher, Razer program.... Who probably are launched at the start of your PC. You will have at a first time to close all of them and launch TES legends withvtracker alone. If it doesn't run, the problem may come from your system. If it run, that's one of the closed programs or on conbination of them are the problem. Restart this program one by one to find which of them is in conflict. 

Have you also tried to stop your anti-virus?

**Comment by extesy** [comment]
@wispydanish Have you tried version `1.0.68`? I have added a handler to show an error message instead of silently crashing.

**Comment by wispydanish** [comment]
Hi @extesy so i tried again today, downloaded latest build. my usual way of running the app caused the same problem to occur.

**However**, when i ran the program directly from the file location as an administrator (rather than from a shortcut) it worked perfectly. 

I have a feeling this was not a problem with the application since I never tried to run directly from the file location before. Either way, thanks so much for your continued help. It was the best tech support I've ever received in my life. Thanks! Feel free to close this ticket now.

**Comment by extesy** [comment]
Glad to help!
