### ISSUE TITLE
Synchronize deck trackers on several computers

### ISSUE THREAD

**Issue by twilightniko** [extesy/DeckTracker#118]
Is it possible to somehow make stats synchronization while using deck tracker on several different computers?

**Comment by emerald000** [comment]
You can probably manage to work something out with Dropbox by sharing your stats files.

**Comment by extesy** [comment]
@twilightniko you can do that using Dropbox and linking `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker` folder on all computers .
