### ISSUE TITLE
Deck Tracker doesn't allow import or export of decks

### ISSUE THREAD

**Issue by FordTheUgly** [extesy/DeckTracker#119]
Hi there
I installed deck tracker on a different laptop including legends.
While it worked fine on the other machine it seems to be having an issue with this one I'm using now
I have following error message: Only working if game client is running and fully initialized.
The error message is for importing and exporting decks.
The game is using my account which is fully authorized and payments have been made in the past.
Running Windows 8.1 64 bit
Browser Chrome, latest build
DeckTracker 1.0.68

Thanks for the help in advance.

[decktracker_error.docx](https://github.com/extesy/DeckTracker/files/1237215/decktracker_error.docx)

# How to report a bug

1. Deck tracker does not work for you at all? There is an [existing issue](https://github.com/extesy/decktracker/issues/21) for this. Look [over there](https://github.com/extesy/decktracker/issues/21), do not create a new issue.
2. Does it crash? Provide a full exception message or a screenshot and what _exactly_ did you do right before that.
3. Some specific feature doesn't work as expected? Read a [reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section and provide debug logs.

In all cases, please provide a detailed step-by-step instructions on how to reproduce your issue. Nobody except you knows specifics of your computer and software you running on it. The less details you provide, the smaller is the chance that your report will be properly investigated.

**Comment by extesy** [comment]
@FordTheUgly If you get error "Only working if game client is running and fully initialized" then you just need to go further into the game interface after it's loaded. For example, open your profile or at least go into the main menu interface.
