### ISSUE TITLE
Problem UDT no export of cards anymore?

### ISSUE THREAD

**Issue by Willson666** [extesy/DeckTracker#122]
Hey guys

u did a great job with this deck trader...

but my one is not willing to export my cards anymore. -.-

i use the bethesda launcher and i know that the tracker worked perfectly at the first day of use.

i am happy about every help u could give me!

greets,
willson

**Comment by extesy** [comment]
@Willson666 Make sure your deck tracker is connected to the game (green). Try restarting both the game and the tracker.
