### ISSUE TITLE
Game counter off by one.

### ISSUE THREAD

**Issue by archon89** [extesy/DeckTracker#126]
Game counter is off by one in some lists. Example lists attached.

8 games played, total shows 7:
![capture](https://user-images.githubusercontent.com/31521943/29945459-824fdeae-8ea1-11e7-8b3f-2a566c30a57a.PNG)

2 games played, shows 1:
![2](https://user-images.githubusercontent.com/31521943/29945517-ba432208-8ea1-11e7-8abf-17d3452e4bb1.PNG)

14 games played, shows 13:
![3](https://user-images.githubusercontent.com/31521943/29945585-f9751602-8ea1-11e7-9bcd-fd73fc28bccb.PNG)

Does not apply to all lists. Other lists show correctly.

**Comment by extesy** [comment]
It's not off-by-one. It's a confusion caused by a tree structure displayed as a flat list. For example, `Scream` is also a `Feln` at the same time. It doesn't make it two different games played. So all counts are correct, it just needs to be displayed as a tree, not a flat list. See #13
