### ISSUE TITLE
Hand size

### ISSUE THREAD

**Issue by wirsmann** [extesy/DeckTracker#128]
Is it possible to have a counter to show how many cards are in your hand?  Find I have to count a lot to make sure how many cards I have in had when I have 8-10 cards to see if I will overdraw.

**Comment by BDubbB** [comment]
Yes, this would be great!

**Comment by Ungaminga** [comment]
bump

**Comment by MarioLiebisch** [comment]
Not sure this is also an issue in the other games, but at least in Legends this is now part of the game's base functionality, so might be something to close.
