### ISSUE TITLE
Unable to Access to Clipboard Error - Latest Version - Windows 8.1

### ISSUE THREAD

**Issue by CDCe** [extesy/DeckTracker#129]
#
![cattura di schermata 16](https://user-images.githubusercontent.com/31575595/29998563-d5b3fc68-902e-11e7-98e6-414177ad258e.png)
 
Hi! i have this error when i click on Export complete collection. The name of the game running is green and i can see the layer in the TESL UI. I just donwload the lates .exe file and instal, running the program firts and them the game.

**Comment by extesy** [comment]
@CDCe Some running application on your computer is blocking access to the clipboard. I can't know what it is, you have to experiment and close that application.

**Comment by Unworldly** [comment]
I have the same problem on my Windows 10 x64 Pro... "Unable to access clipboard".
UniversalDeckTracker version 1.0.78, Antivirus and Firewall is off.
