### ISSUE TITLE
Missing source code for DeckTracker.InGame.dll?

### ISSUE THREAD

**Issue by gaksen** [extesy/DeckTracker#131]
There is dll named DeckTracker.InGame.dll in downloaded version of deck tracker. But I can't find source code for this dll on github. Is it here?

**Comment by extesy** [comment]
Nope, it's not here. You can take this dll from the distributive and use in combination with the manually compiled code.

**Comment by gaksen** [comment]
I'd like to add a few things to in game interface that would be useful in draft process (number of units, weapons etc.) So I need source code to be able do that. Are you going to publish source code of DeckTracker.InGame.dll in foreseeable future?

**Comment by extesy** [comment]
Eventually, may be. Off-game client UI also needs work and despite several offers of help I'm yet to see a single contribution from anyone.

**Comment by twizzl** [comment]
I abandoned helping with this project due to not having DeckTracker.InGame.dll source, I also requested this from you a while back. The external UI isn't an issue to me and I don't care to work on it, however the in game one is and I would prefer to work that.
