### ISSUE TITLE
ERROR: "Something went wrong, access denied"

### ISSUE THREAD

**Issue by Drenchkat** [extesy/DeckTracker#132]
Hello,

I am receiving the following error message when I try to run the DeckTracker. I have tried to run the tracker BEFORE and AFTER I launch the game including the launcher itself. Do you have any advice? Thanks in advance!

-Drench

![image](https://user-images.githubusercontent.com/32115133/30621579-e0641f00-9d79-11e7-984c-a49ad83b455e.png)

**Comment by extesy** [comment]
@Drenchkat Something on your computer (maybe antivirus or other software or specific user permissions) prevent deck tracker from attaching to the game. I am not able to perform remote diagnostics on your computer so you'll have to figure out what might cause this.

**Comment by Drenchkat** [comment]
Thanks I will try to keep checking my system, not sure what it could be.
