### ISSUE TITLE
Latest TESL patch 1.67 breaks Deck Tracker

### ISSUE THREAD

**Issue by Headcrab4711** [extesy/DeckTracker#134]
Great program, however - doesn't work for me.

I have installed Deck Tracker, game is detected correctly (Elder Scrolls Legends was written blue for 2-5secs than turned green).

I can import new decks into the game, as well as export all my decks to Deck Tracker - but:
I am not able to enable the overlay, neither in Windows, nor ingame (F1-F6 does not work, too).

I have installed the Microsoft Access data, like recommended by the FAQ.
I am unsing a 3rd party anti virus, but the Deck Tracker has been put on exeption list.

Any hints how to get this working?
Thank you so much.

![grafik](https://user-images.githubusercontent.com/32375775/30993319-a59df0b2-a4ae-11e7-9a17-12faf0a635b3.png)

**SOLUTION (from @extesy): Update to version [1.0.69](https://github.com/extesy/DeckTracker/releases/tag/1.0.69) or later.**

**Comment by nathanpaulyoung** [comment]
I'm 90% sure this is related to the 1.67 update today. It was working fine for me yesterday and does not work today post-update.

**Comment by Man-s** [comment]
I was just about to post this and I have to agree with nathanpaulyoung. I've been using the program for many months and today is the first time I've had any issues. I'm pretty sure the latest Elder Scrolls Legends 1.67 update messed something up. The symptoms are similar for me. The Deck Tracker identifies the game running but there is no overlay in-game and no stat recording. Exporting the collection still works though.

**Comment by Skift02** [comment]
I too was about to post this issue. I have been using this great program for months and now I cannot get an overlay to save my life. In addition to this, it will not detect any stat recordings as well.

**Comment by wirsmann** [comment]
Yeah the update broke it for me too.

**Comment by extesy** [comment]
Everyone, please try the new build `1.0.69`: https://github.com/extesy/DeckTracker/releases/tag/1.0.69

**Comment by wirsmann** [comment]
Working for me, awesome job!

**Comment by extesy** [comment]
Cool, thanks for confirming! I'll keep this issue open until tomorrow in case if anyone else stumbles upon it.

**Comment by SithLordOfSnark** [comment]
I still get the issue with it not loading at all.

**Comment by Headcrab4711** [comment]
works for me, too - thanks for fixind and keep up the good work please :)

**Comment by Man-s** [comment]
It is indeed back to normal. Thanks again extesy!
