### ISSUE TITLE
Can't download .exe or .msi

### ISSUE THREAD

**Issue by McJoker69** [extesy/DeckTracker#135]
I would really love to give DeckTracker a try, however both the .exe and the .msi time out after downloading about 109KB (at about 2.9KB/sec, though any of my other downloads run at much higher speeds), then fail.

This happens under Firefox, Chrome, Edge and IE, I have no issues with any other downloads, so I'm guessing it's a GitHub issue? Have my reasons for preferring the installation files over the source code, so are there any other options, @extesy ?

**Comment by extesy** [comment]
@McJoker69 You can try using some proxy or VPN or just try later. I can't be responsible for the connection speed between your home and github.com. Compiling from source code won't give you a complete product because one dll (that draws in-game ui) is not open sourced.

**Comment by McJoker69** [comment]
Didn't remotely think that, however I figured you might be aware of any potential reasons. 

A proxy or VPN wouldn't change connection speeds in a positive manner, and I haven't had the issue with other projects on GitHub before. Merely wanted to know if there were any other options. I guess not.

**Comment by extesy** [comment]
> A proxy or VPN wouldn't change connection speeds in a positive manner

You would be surprised...
