### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by TouchMe-Sama** [extesy/DeckTracker#138]
# How to report a bug

1. Deck tracker does not work for you at all? There is an [existing issue](https://github.com/extesy/decktracker/issues/21) for this. Look [over there](https://github.com/extesy/decktracker/issues/21), do not create a new issue.
2. Does it crash? Provide a full exception message or a screenshot and what _exactly_ did you do right before that.
3. Some specific feature doesn't work as expected? Read a [reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section and provide debug logs.

In all cases, please provide a detailed step-by-step instructions on how to reproduce your issue. Nobody except you knows specifics of your computer and software you running on it. The less details you provide, the smaller is the chance that your report will be properly investigated.

**Comment by TouchMe-Sama** [comment]
I start UDT and then TESL, and this message appears for UDT.

Something went wrong...
Object reference not set to an instance of an object

![sem titulo](https://user-images.githubusercontent.com/30402860/31311457-da1c1ac8-ab82-11e7-8464-d586996853c0.png)

That's it, I don't how this started, I already reinstalled TESL and UDT.

**Comment by TouchMe-Sama** [comment]
Today I tried again and another error window popped up after clicking "ok" in the one from the picture, it was "Something went wrong... Leaked a Mutex". Obviously, UDT crashed just like before and I still can't use it...

![sem titulo](https://user-images.githubusercontent.com/30402860/31397472-86d4cc7a-adbc-11e7-9351-18c32ca048e0.png)

Waiting your reply, extesy. Thanks

**Comment by TouchMe-Sama** [comment]
I just deleted the UDT file in C:\Users\Gabriel\AppData\Roaming and it's working again... Thanks

**Comment by extesy** [comment]
@TouchMe-Sama Cool! Thanks for confirming.

**Comment by Rwendoll** [comment]
extesy I get this error in the log can you help me?  " Exception happened while invoking DeckTracker.InGame.dll"

**Comment by BlessedPrayer** [comment]
Hi @extesy, I also have the same problem as in the first picture... "Something went wrong... Referencia a objeto no establecida como instancia de un objeto (spanish)". It's quite strange, because I was using UDT for a long time. Just crashed yesterday and I'm trying to do everything to restore it but I don't know how fix it. I'm looking in all the the issue tickets linkeds but I didn't find a solution. Some help please. Many thanks.

**Comment by Darkchilde** [comment]
Hi @extesy,

I seem to be having an issue with Universal Deck Tracker after the last update to TESL. I've tried uninstalling and reinstalling the .exe file several times, however, that hasn't changed anything. I've also tried installing the 2016 Microsoft Access runtime, as I've seen that resolves some issues. Would you have any other suggestions I can try?

Running: Windows 10 Pro (64-bit)

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/11858480/39399880-d36a5256-4ada-11e8-878d-124282958d71.png)

I hope you can help me resolve this matter, as I really enjoy using your tool. I look forward to your response.
