### ISSUE TITLE
How does DeckTracker manage to recognize cards?

### ISSUE THREAD

**Issue by woctezuma** [extesy/DeckTracker#140]
I don't think there is any explanation written in the README regarding the method which you used to build DeckTracker. Is it only intercepting low-level signals of some sort, or is it actually working by recognizing the cards displayed on the screen (which would surprise me)?

Thanks for your attention.

**Comment by extesy** [comment]
@woctezuma It hooks into the game and inspects client-server communication, the messages that the game sends and receives. It does not look at the screen.
