### ISSUE TITLE
String Error when opening DeckTracker

### ISSUE THREAD

**Issue by beefystew89** [extesy/DeckTracker#141]
Sorry if this is a repeat question, but I couldn't find it listed anywhere yet. Previously DeckTracker worked fine for me. It randomly stopped, not even after an update to TES. It says unexpected string. I have attached a screen shot with the error centered. Thanks for the help. 

![copy of 20171013_224850](https://user-images.githubusercontent.com/32785786/31572069-5a029ca2-b06b-11e7-9482-03445fed90f6.jpg)

**Comment by extesy** [comment]
@beefystew89 Sorry, I don't know what that error means. Try deleting the config file at `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\config.json` location.

**Comment by beefystew89** [comment]
@extesy Thanks for the suggestion, it worked after I deleted a couple more of the appdata files. Runs great again.
