### ISSUE TITLE
Can't Export Deck, error message oops something went wrong

### ISSUE THREAD

**Issue by Tribalpanda** [extesy/DeckTracker#143]
I have downloaded the exe file and when I try to load the game up with the Deck tracker open it doesnt load the game at all just a blank black screen. When I load up deck tracker after the game, it says its connected to the game, and it has the green writing in the top right corner but when i try export my deck, says oops something went wrong. I have tried to export at main menu, on profile page and in a casual game as im battling against another player. Any ideas how to get it to work? 
Thanks in advance :)

**Comment by HeartOfSun** [comment]
I have same problem

**Comment by extesy** [comment]
What is the exact message? Please copy entire message or provide a screenshot.

**Comment by MrCodewell** [comment]
This is what I get when I try to get my collection.  
![something_wrong](https://user-images.githubusercontent.com/24494810/32512956-9da74052-c3c6-11e7-8123-a0adb18f233d.png)

**Comment by extesy** [comment]
I'll add better logging in the next release to help diagnose the problem.

**Comment by extesy** [comment]
Can you please try version [1.0.70](https://github.com/extesy/DeckTracker/releases/tag/1.0.70) and let me know the last few errors in `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\error.log` file?

**Comment by HeartOfSun** [comment]
1.0.70 works for me, thank you!
