### ISSUE TITLE
ESL do not load with Decktracke

### ISSUE THREAD

**Issue by Omenofis** [extesy/DeckTracker#144]
I have search and try the solutions that u suggest but still my problem remains, I load decktracker 1.0.69 and then loading ESL and loading stops in black screen with bottom right deck tracker 1.0.69 logo
ESL game works perfectly without decktracker.
i add the errror file from roaming

2017-10-18T12:10:34.1954816Z|System.ComponentModel.Win32Exception (0x80004005): Δεν επιτρέπεται η πρόσβαση
   σε System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.get_HasExited()
   σε DeckTracker.LowLevel.ProcessMonitor.OnTimer()
   σε DeckTracker.LowLevel.ProcessMonitor.<>c.<Start>b__8_0(Object sender, EventArgs args)
   σε System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   σε System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   σε System.Windows.Application.RunDispatcher(Object ignore)
   σε System.Windows.Application.RunInternal(Window window)
   σε System.Windows.Application.Run(Window window)
   σε DeckTracker.App.Main()
2017-10-18T12:15:27.1945796Z|System.ComponentModel.Win32Exception (0x80004005): Δεν επιτρέπεται η πρόσβαση
   σε System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.get_HasExited()
   σε DeckTracker.LowLevel.ProcessMonitor.OnTimer()
   σε DeckTracker.LowLevel.ProcessMonitor.<>c.<Start>b__8_0(Object sender, EventArgs args)
   σε System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   σε System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   σε System.Windows.Application.RunDispatcher(Object ignore)
   σε System.Windows.Application.RunInternal(Window window)
   σε System.Windows.Application.Run(Window window)
   σε DeckTracker.App.Main()
Exception happened while invoking DeckTracker.InGame.dll
 2017-10-18T13:56:49.5589158Z|System.ComponentModel.Win32Exception (0x80004005): Δεν επιτρέπεται η πρόσβαση
   σε System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.get_HasExited()
   σε DeckTracker.LowLevel.ProcessMonitor.OnTimer()
   σε DeckTracker.LowLevel.ProcessMonitor.<>c.<Start>b__8_0(Object sender, EventArgs args)
   σε System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   σε System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   σε System.Windows.Application.RunDispatcher(Object ignore)
   σε System.Windows.Application.RunInternal(Window window)
   σε System.Windows.Application.Run(Window window)
   σε DeckTracker.App.Main()
2017-10-18T13:56:52.4403563Z|System.Threading.AbandonedMutexException: Leaked a Mutex!
   σε Squirrel.SingleGlobalInstance.Finalize()
2017-10-18T13:57:08.0559818Z|System.ComponentModel.Win32Exception (0x80004005): Δεν επιτρέπεται η πρόσβαση
   σε System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.get_HasExited()
   σε DeckTracker.LowLevel.ProcessMonitor.OnTimer()
   σε DeckTracker.LowLevel.ProcessMonitor.<>c.<Start>b__8_0(Object sender, EventArgs args)
   σε System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   σε System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   σε System.Windows.Application.RunDispatcher(Object ignore)
   σε System.Windows.Application.RunInternal(Window window)
   σε System.Windows.Application.Run(Window window)
   σε DeckTracker.App.Main()
2017-10-18T13:58:13.5388812Z|System.ComponentModel.Win32Exception (0x80004005): Δεν επιτρέπεται η πρόσβαση
   σε System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   σε System.Diagnostics.Process.get_HasExited()
   σε DeckTracker.LowLevel.ProcessMonitor.OnTimer()
   σε DeckTracker.LowLevel.ProcessMonitor.<>c.<Start>b__8_0(Object sender, EventArgs args)
   σε System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   σε System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   σε System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   σε MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   σε System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   σε System.Windows.Application.RunDispatcher(Object ignore)
   σε System.Windows.Application.RunInternal(Window window)
   σε System.Windows.Application.Run(Window window)
   σε DeckTracker.App.Main()

**Comment by Tribalpanda** [comment]
seems to have same problem as me? And when you load the game first it doesn't let you export decks?

**Comment by Omenofis** [comment]
if i load the game first and then the decktracker then even if decktracker acknowledge the game (is green) and the logo of decktracker is bottom right  it doesnt works. Game running perfectly but decktracker is not communicate .. no decks found in decktracker nothing shows up...

**Comment by extesy** [comment]
@Omenofis  `Δεν επιτρέπεται η πρόσβαση` means "access is not allowed" - so there's probably some antivirus running on your machine or your user doesn't have permissions by some reason. Try running as  admin and/or disabling antivirus and/or adding UDT to exceptions.

**Comment by Omenofis** [comment]
i have seen it, and try to disable the antivirus, try to reinstall it with disabled antivirus also still the same problem and ofc always run the decktracker as admin .. so something elsh is the problem here.

**Comment by extesy** [comment]
Whatever it is, it is specific to your machine and a few other unfortunate people. For thousands others UDT works fine and I have no idea how to diagnose the problem on your machine. I only see that UDT can't open the game process on your machine with "access denied" error. It doesn't happen on mine, it doesn't happen on most people's PCs. Sorry, but at this moment I don't know how to help you.
