### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by GruesomeCthulhu** [extesy/DeckTracker#147]
I had it working.  It detected the TESL just fine, but it wouldn't fetch my collection so i could export it.  So, i uninstalled then tried to re-install.  Now I just get an Installation failed error.
![image](https://user-images.githubusercontent.com/33366326/32402808-2d19e5f4-c102-11e7-8f2e-b6a21e075a24.png)
here is the setup log idk if it'll help but there it is...
[SquirrelSetup.log](https://github.com/extesy/DeckTracker/files/1442963/SquirrelSetup.log)
would really like to be able to use this tool

**Comment by extesy** [comment]
@GruesomeCthulhu Delete `C:\Users\The Fam\AppData\Local\UniversalDeckTracker` folder manually then reinstall. Make sure you don't have deck tracker already running.
