### ISSUE TITLE
Deck Tracker no longer placing visuals on Eternal with latest Update.

### ISSUE THREAD

**Issue by jonahveil** [extesy/DeckTracker#149]
subj

**Comment by extesy** [comment]
@jonahveil Thanks for the heads up. I'll fix it when I get back home later today.

**Comment by jonahveil** [comment]
There was a thread on Reddit about them not being ok with Deck trackers due to them doing things they shouldnt. but the comment was made like 3 months ago, didnt know if it was a concern of yours or not

**Comment by extesy** [comment]
https://github.com/extesy/DeckTracker/releases/tag/1.0.71 should be working with latest Eternal patch.

As for the comment, I've already responded at that time - this was briefly mentioned by Scarlatch in discord without any further explanations. It's not an official statement, it's not a word of god, there was no follow-up to that, so take it as you will.

There are thousands of active users of this tracker and I'm sure everyone in DWD/Bethesda is well aware of that. It's not hard to contact me and if they wanted do they would've done so already.
