### ISSUE TITLE
Won't Load - Gives Error

### ISSUE THREAD

**Issue by SithLordOfSnark** [extesy/DeckTracker#150]
I constantly get this error when trying to load UDT:

Something went wrong....

Object reference not set to an instance of an object.

**Comment by extesy** [comment]
@SithLordOfSnark Which version? Did it work in the past?

**Comment by extesy** [comment]
@SithLordOfSnark Make sure you are using latest version (1.0.71 at the moment) and please also provide the contents of `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\error.log` file.

**Comment by SithLordOfSnark** [comment]
I deleted the config and archetypes files and now it seems to work just fine.
