### ISSUE TITLE
Deck tracker blocked by Bitdefender

### ISSUE THREAD

**Issue by Man-s** [extesy/DeckTracker#151]
I just used the new 1.0.71 version when playing TESL and it was immediately blocked by Bitdefender, tagged as malware. Never had any issues regarding Bitdefender with previous versions.

**Comment by MarioLiebisch** [comment]
Which file does it block? Does it tell you?

**Comment by extesy** [comment]
@Man-s Sorry, I don't use Bitdefender myself so the only suggestion I have is to submit it as false positive if it has this ability.

**Comment by MarioLiebisch** [comment]
FYI [I zipped the latest version and sent it to virus total](https://www.virustotal.com/#/file/c28c9eff43e7c1313696064f8b034e2df6345f1e374438927124a913dec667b6/detection): nothing, not even false positives (not on Bit Defender either). Personally I suspect some behavioral analysis noticed the hook code to inject into the games and/or the updater and considered it potential harmful (which it could be with other intentions).

**Comment by extesy** [comment]
Well, there's nothing I can do about some antiviruses being over-suspicious :(

**Comment by Man-s** [comment]
Sorry, I only managed to get to the computer again right now to reply to your request. It blocked the .exe file and quarantined all dlls as far I as could tell. At the same time it blocked a "csc.exe" on the Microsoft .Net framework folder for some reason?! I have the security settings set as standard, nothing aggressive, just found it odd and thought you should be aware. I'm not aware of any way to submit it as a false positive but I added it to the exclusion list.

 Just to be clear, I opened this issue for you to have this information available, I'm not suspicious of the program and I, like I did in the past, thank you for your hard work on it. :)

**Comment by extesy** [comment]
I appreciate the info, @Man-s! And thank you for your "thank you"! :)

**Comment by MarioLiebisch** [comment]
Out of curiosity looked a bit into it and considering it complains about `csc.exe` it's most likely triggered by the just in time compilation of some code for the `DeckClassifier` class. This is completely harmless, but something malware might do as well to work around anti-malware programs by dynamically creating and mutating code on the target machine..
