### ISSUE TITLE
Clockwork City - Something went wrong...

### ISSUE THREAD

**Issue by neonsighs** [extesy/DeckTracker#157]
DeckTracker shows that the game client is running but ever since the expansion, when i try to export my deck i get the error "Something went wrong... Please wait until the game client is fully initialized"

**Comment by oraculus** [comment]
same error here

**Comment by extesy** [comment]
@neonsighs @oraculus Try UDT release `1.0.72` - https://github.com/extesy/DeckTracker/releases/tag/1.0.72

**Comment by oraculus** [comment]
can confirm, 1.0.72 works fine. Great job and thank you!
