### ISSUE TITLE
APPCRASH (d3d9.dll) with update KB4051963 on Windows 10 Home 1709

### ISSUE THREAD

**Issue by Zephyr-Wrangler** [extesy/DeckTracker#158]
When I started UDT I instantly got "Universal Deck Tracker has stopped working" and a half/strangely drawn UDT window:

![udt error](https://user-images.githubusercontent.com/34259432/33588935-a510fcd4-d9c9-11e7-8503-55531435098f.PNG)

Log:

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: UniversalDeckTracker.exe
P2: 1.0.72.0
P3: 5a1f7859
P4: d3d9.dll
P5: 10.0.16299.98
P6: e2fbf0fc
P7: c0000096
P8: 000481d1
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAEB9.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_UniversalDeckTra_4c4ee1e5d24f01f81b7dd2ca9404d92463774b_aab4c65b_21984dc9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5886decd-9680-4aa9-8046-ba78f852876f
Report Status: 100
Hashed bucket: 

Other applications were also not working like the GUI for Intel Rapid Storage.

This is on Windows 10 Home 1709, when I uninstalled KB4051963 the build went back to 16299.64 ( I think it was 16299.98 previously), UDT and other apps are now working again.

https://support.microsoft.com/en-au/help/4051963/windows-10-update-kb4051963 mentions "- Addressed a performance regression when users run full-screen Microsoft DirectX 9 games and applications", which may be relevant.

I'll not install any updates until whatever, I just thought I should give you a heads up.

Thanks very much for the great app.

**Comment by extesy** [comment]
I think this problem is specific to your machine, maybe some software conflict. I have this patch installed and everything works for me, including Intel RST drivers.

**Comment by Zephyr-Wrangler** [comment]
Okay thanks, I'll look in to it.
