### ISSUE TITLE
[FReq] User-generated deck archetypes

### ISSUE THREAD

**Issue by apoapostolov** [extesy/DeckTracker#161]
It is possible for DeckTracker to expose to users to define their own deck archetypes so they get very accurate descriptions inside the overlay? This could become a side-project for dedicated players to maintain a list on github that the app downloads on each launch. 

The way I have imagined it, it could work like this:

All archetypes are stored in a text file format and consist of the following elements:
- Sigil Colors, maybe even use MtG BWRUG
- List of Cards, defined as set-number (1-23, as used in EternalWarcry)
- Finally a name string and a placement order (1-X). This is very powerful as it allows several matching archetypes to overlap and create a composite archetype. For example, "Praxis" is a RW sigil with no cards and placement 1, "Chalice" is defined by the card Chalice and placement 2, "Lifesteal" is defined by number of lifesteal cards and placement 3. A deck that somehow matches all these would be named "Praxis Chalice Lifesteal". 
- Fuzzy logic algorithm that recognizes partial archetypes by % of matching cards and prefers one archetype over another. If the matching is not strict, it could apply a (?) to the word. For example, a Praxis Chalice deck that has only 1 of 5 defined Lifesteal cards, would be named "Praxis Chalice Lifesteal(?)"

I would love to discuss this feature more before set as enhancement, to improve the methodology. Thanks in advance!

**Comment by extesy** [comment]
@apoapostolov It's already in the [FAQ](https://github.com/extesy/DeckTracker#faq-frequently-asked-questions):

> * How to change detected deck archetypes or add new ones?
> 
> Create or update C:\Users\{profile}\AppData\Local\UniversalDeckTracker\decktypes.txt file. If you like your changes, please contribute back to the community by sending a pull request.

**Comment by apoapostolov** [comment]
Thanks, looks like it has everything covered except multiple archetypes being able to be matched at once and combine their name. Is this document exposed in the app installation so users can add additional ones?

**Comment by apoapostolov** [comment]
This is great, I wasn't aware this was already covered in such depth.

The only thing I see missing here is the ability to merge several archetypes by combining their names. I think this is a very powerful feature, since typically the name of archetypes is a combination of several aspects, defined by color, by enough cards of a specific combo/type/rule/keyword, etc.

I would love to see the following features added to decktypes.txt:

1) ability to define priority level to the name of an archetype - so archetypes with different priority levels can be combined in real time. I noticed the current definition uses | as a priority indent but I don't think archetypes can combine their names right now. 
2) Cards.NotContains for a blacklist functionality. 

Let me know if it is best to close this issue and open a focused one on new decktypes.txt commands.

**Comment by extesy** [comment]
The expression after the last `|` is a regular C# expression so it supports everything C# supports. Syntax for NotContains in C#: `!Cards.Contains(...)`, etc.

**Comment by extesy** [comment]
Merging of artifacts is not supported because of a few reasons: 1) With many matches it's not possible to display in UI-friendly way, 2) It's hard to define a syntax for this: when to merge, when to not merge, etc.

**Comment by apoapostolov** [comment]
Okay that makes sense. Thanks for the explanation.
