### ISSUE TITLE
Crashes after game update 1.69.0.3540

### ISSUE THREAD

**Issue by kirmir** [extesy/DeckTracker#163]
Game version: 1.69.0.3540

Steps:
1. Run the game
2. Start the tracker
3. Click 'Export Full Collection'

Exception: Something went wrong... The given key was not present in the dictionary.

Probably, the reason is the new cards added in the latest patch. Few cards with the new unique art available in the Store.

**Comment by extesy** [comment]
@kirmir Doesn't crash for me. Make sure you give it a minute after starting a game before you try to export your collection.

**Comment by apoapostolov** [comment]
Same issue here however for Eternal 1.27.0.3666 after Set 3 release today.

**Comment by kirmir** [comment]
@extesy Tried to wait and open collection before pressing Export. Works fine. Thanks.
