### ISSUE TITLE
Deck tracking not working after latest Eternal update

### ISSUE THREAD

**Issue by fmoraes74** [extesy/DeckTracker#164]
The deck tracker doesn't appear to be showing the full deck at least when playing Gauntlet in Eternal after the latest update. The shown deck is only partially shown as cards are drawn.

**Comment by extesy** [comment]
That was kinda expected with the huge changes they made. Will fix later today.

**Comment by extesy** [comment]
Hm... The changes are even more substantial than I expected. Fixing it will take a bit more time.

**Comment by fmoraes74** [comment]
Any update on the issue?

**Comment by G3Kappa** [comment]
If you elaborated an idea for what needs to be done and you want to share it, I can help and I'm sure many others can as well.

**Comment by extesy** [comment]
I just didn't have time to look into it yet: holidays, vacations, family...

**Comment by G3Kappa** [comment]
Pardon, you're right. Please take your time and keep us updated!

**Comment by extesy** [comment]
Can someone please try [build 1.0.73](https://github.com/extesy/DeckTracker/releases/tag/1.0.73) before I mark it for general release?

**Comment by kellwintern** [comment]
Working smoothly in Casual and Ranked. As for Gauntlet the first time the decklist showed up as per usual but for subsequent runs the decklist was incomplete similar to G3Kappa's post above.

**Comment by fmoraes74** [comment]
I've only tried in Gauntlet but the results match what others have said. I've got the deck list inconsistently, almost like the issue I've opened for Forge.

**Comment by extesy** [comment]
Interesting... Ok, let me take a look more. I've only tested it with one game in Gauntlet.

**Comment by extesy** [comment]
Ok, build 1.0.74 should work in Gauntlet too.
