### ISSUE TITLE
Small size for 4k Monitor, Can you make this larger sized?

### ISSUE THREAD

**Issue by TJourd** [extesy/DeckTracker#166]
# How to report a bug

1. Deck tracker does not work for you at all? There is an [existing issue](https://github.com/extesy/decktracker/issues/21) for this. Look [over there](https://github.com/extesy/decktracker/issues/21), do not create a new issue.
2. Does it crash? Provide a full exception message or a screenshot and what _exactly_ did you do right before that.
3. Some specific feature doesn't work as expected? Read a [reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section and provide debug logs.

In all cases, please provide a detailed step-by-step instructions on how to reproduce your issue. Nobody except you knows specifics of your computer and software you running on it. The less details you provide, the smaller is the chance that your report will be properly investigated.

**Comment by TJourd** [comment]
Hi, My 4k Monitor has a small sized window for deck tracker. Would it be possible to make the window adjustable? Or automatically adjust according to monitor resolution?
Thanks!

**Comment by extesy** [comment]
@TJourd Please read https://github.com/extesy/DeckTracker#faq-frequently-asked-questions, specifically "how to resize deck lists".
