### ISSUE TITLE
Window resize option to small to access easily, needs to be enlarged.

### ISSUE THREAD

**Issue by TJourd** [extesy/DeckTracker#168]
# How to report a bug

1. Deck tracker does not work for you at all? There is an [existing issue](https://github.com/extesy/decktracker/issues/21) for this. Look [over there](https://github.com/extesy/decktracker/issues/21), do not create a new issue.
2. Does it crash? Provide a full exception message or a screenshot and what _exactly_ did you do right before that.
3. Some specific feature doesn't work as expected? Read a [reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section and provide debug logs.

In all cases, please provide a detailed step-by-step instructions on how to reproduce your issue. Nobody except you knows specifics of your computer and software you running on it. The less details you provide, the smaller is the chance that your report will be properly investigated.

**Comment by TJourd** [comment]
Title says it all, I spent many clicks attempting to click and drag the windows size. This area of click/hold/drag needs to be enlarged or at least made easy to see(I use 4k). Even the 1080 version it is difficult to resize.  

Possible fix: make it so op can click/hold/drag easier, or use a simple right clicking twice to up-size a certain amount say 10 pixels each time a person does this action. Why this was made so difficult to accomplish such a basic task. 

I am not alone in this problem as after watching other people in their videos showing they too are having the same problem with resizing.

Thanks for you time to affect a repair of this problem to a otherwise really great program.

**Comment by extesy** [comment]
Hi @TJourd, this problem and a few possible options are already being discussed in #110. I also wrote down reasons why the fix is not as simple as it seems.
