### ISSUE TITLE
ESL Terms of Service

### ISSUE THREAD

**Issue by waitthisisntmtg** [extesy/DeckTracker#17]
Hey Ex,

I noticed your tracker works for ESL also, but another redditor told me it breached TOS. Have you heard thats the case for ESL? I know it wasn't for Eternal.

Lemme know!
Ethan

**Comment by extesy** [comment]
@waitthisisntmtg That other redditor is wrong. Using this specific tracker doesn't breach TOS because it doesn't modify any game files. There are other deck trackers which patch game files so another redditor was thinking about those trackers. This tracker is safe to use.
