### ISSUE TITLE
My decklist panel has disappeared and won't come back

### ISSUE THREAD

**Issue by CWIComrade** [extesy/DeckTracker#172]
I have no idea how to reproduce this issue cos I didn't notice when it first happened. The deck list only appears for my enemies deck, not mine. Tried restarting TESL, Deck Tracker, uninstalling deck tracker and reinstalling. Still the same

**Comment by extesy** [comment]
@CWIComrade You can either delete config file (see https://github.com/extesy/DeckTracker#faq-frequently-asked-questions) or press F2 to show your deck (https://github.com/extesy/DeckTracker#keyboard-shortcuts)
