### ISSUE TITLE
Current license contradicts help requests and prevents pull requests

### ISSUE THREAD

**Issue by MarioLiebisch** [extesy/DeckTracker#173]
So far the DeckTracker is released under a CC NC-ND license. At the same time, there are many open issues and you're obviously looking for help regarding these (at least [according to some issue tags](https://github.com/extesy/DeckTracker/issues?q=is%3Aopen+is%3Aissue+label%3A"help+wanted")).

However, the current license denies the creation of derivatives, contradicting this request, as anyone trying to do so would basically violate the conditions in section 2 a 1 b:

```
Section 2 -- Scope.

  a. License grant.

       1. Subject to the terms and conditions of this Public License,
          the Licensor hereby grants You a worldwide, royalty-free,
          non-sublicensable, non-exclusive, irrevocable license to
          exercise the Licensed Rights in the Licensed Material to:

            a. reproduce and Share the Licensed Material, in whole or
               in part, for NonCommercial purposes only; and

            b. produce and reproduce, but not Share, Adapted Material
               for NonCommercial purposes only.
```

Just to reword this for clarity:

* Forking the GitHub repository or cloning it doesn't violate the license (as it's a 1:1 copy).
* Making local changes doesn't violate the license either.
* Uploading the changes for a pull request (or sharing them any other way) violates the licensing terms.

I'm no lawyer, but that's how I understand the license.

I understand the general idea, basically avoiding multiple versions, making it easier for people to find the correct/legitimate one (or possibly even avoid getting a manipulated one), but then again it's not that uncommon for many other projects to do that without issues.

Is there anything speaking against a change to a similar license that allows derivatives, e.g. [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)? This way people would still have to credit the original project, use same terms, etc. to avoid confusion about the origins, but they could actually improve the program and share the changes back to the community.

**Comment by extesy** [comment]
@MarioLiebisch Thanks for the question. Yes, I am aware of this limitation of this license and as you have correctly guessed the main reason was to avoid other projects "borrowing" critical parts of this project. This is the closest matching license I could find.

I don't mind pull requests, but I want to avoid complete and partial forks. Perhaps I should add explicit exception to the license text that pull requests are allowed but IANAL and I don't know how to do that correctly. I don't plan to enforce this license at all unless I see some other public project that is clearly based on this one.
