### ISSUE TITLE
MSI Installer failing silently

### ISSUE THREAD

**Issue by MarioLiebisch** [extesy/DeckTracker#178]
You basically get your usual UAC prompt, confirm, then get a short look at the extraction dialog and everything disappears.

The uninstaller entry in add/remove programs is properly created, but I couldn't find any of the other files (where should they go? ProgramData? local AppData?) and there doesn't seem to be any start menu shortcuts either.

The executable package/installer is working fine.

(Windows 10 Pro Fall Creators Update x64)

**Comment by extesy** [comment]
@MarioLiebisch Start typing "Universal" or "Deck Tracker" in your Windows search bar. It has installed and it has created an icon.

**Comment by MarioLiebisch** [comment]
Nope, that's what I tried first and they weren't there. Where are the files supposed to go when using the global installer?

**Comment by extesy** [comment]
`C:\Users\{profile}\AppData\Local\UniversalDeckTracker`

**Comment by MarioLiebisch** [comment]
Definitely wasn't there. That folder only had `updater.exe` and `.dead` (or similar name) from a previous installation.
