### ISSUE TITLE
Deck Tracker problem with latest Eternal patch 

### ISSUE THREAD

**Issue by Palaryel** [extesy/DeckTracker#183]
If the game loads while the Deck Tracker is running OR if the Deck Tracker is started after the game already loaded up an automatic disconnection happens. 

Apparently the latest patch did something to force close the game if it detects Deck Tracker (or just close if anything reads its memory?)

**Comment by Chesspieceface** [comment]
confirmed

**Comment by shamanix7** [comment]
Is this the end of the Decktracker for Eternal? Seemed as it is inteded by dwd. what a shame

**Comment by Palaryel** [comment]
If it would have been intentional they would have mentioned it in the patch notes. It wasn't mentioned, hence its still not illegal.

**Comment by extesy** [comment]
I know, just haven't looked into this yet. DWD if often making fairly broad code changes to Eternal in their patches. I'm trying to write as generic code as possible so that it's not affected by minor patches but it's not always possible.

**Comment by extesy** [comment]
Work in progress build: https://github.com/extesy/DeckTracker/releases/tag/1.0.75

**Comment by SupernovaDML** [comment]
With the work in progress build I get an error when trying to export the full collection: "The given key was not present in the dictionary."

**Comment by fverdoja** [comment]
version 1.0.75 works perfectly here

**Comment by Chesspieceface** [comment]
1.0.75 does not prevent login, but it also cannot read my decklist while I am streaming with the waystone extension

**Comment by Chesspieceface** [comment]
@extesy Have you touched 1.0.75 in the last two weeks?  Are you going to?

**Comment by extesy** [comment]
Try `1.0.76`.
