### ISSUE TITLE
Deck Tracker crashes immediately when opened

### ISSUE THREAD

**Issue by fisheye765** [extesy/DeckTracker#186]
I used to use deck tracker quite a lot (mainly for updating collection manager), but when I went to open it (UniversalDeckTracker.exe), after a long hiatus from TESL, it crashed. So I uninstalled it and installed the latest version (1.0.74, UniversalDeckTracker.exe). The tracker crashes immediately after having been installed (as soon as it is opened?) and I have noticed there is no config.json file at the location "C:\Users\[username]\AppData\Roaming\UniversalDeckTracker".

Below is a screenshot of the application right after having been installed and opened (automatically).
![app crash](https://user-images.githubusercontent.com/35798328/37243607-6604ce10-24b7-11e8-85a4-034a01b2192c.PNG)

Thanks in advance.

**Comment by fisheye765** [comment]
bump

**Comment by extesy** [comment]
Try `1.0.76`, this problem might be specific to your machine.

**Comment by fisheye765** [comment]
Problem fixed with update 1.0.78 (or it was the recent windows update in May?)
Anyways, glad it's fixed, Keep up the good work!!!
