### ISSUE TITLE
not tracking any games

### ISSUE THREAD

**Issue by shamanix7** [extesy/DeckTracker#187]
With the 1.0.75 Version, DeckTracker is not showing me any games. According games.log they are present.
[error.log](https://github.com/extesy/DeckTracker/files/1811831/error.log)
[games.log](https://github.com/extesy/DeckTracker/files/1811832/games.log)

**Comment by Sodiumbrella** [comment]
I don't know about the logs, but DT isn't tracking my decks either in Eternal.

**Comment by shamanix7** [comment]
Only Forge games are tracked. All the others (Ranked, Draft, Gauntled, Campain) are not tracked.

**Comment by extesy** [comment]
Should work better now in `1.0.76`, please open a new ticket for specific problems.
