### ISSUE TITLE
How can I see win rates??

### ISSUE THREAD

**Issue by redsky1205** [extesy/DeckTracker#189]
When I play TESL, I want see win rate like this
![tracker](https://user-images.githubusercontent.com/37565512/37633869-73bb29fa-2c37-11e8-929c-ede795a25e88.png)

but i can only see this.
![mine](https://user-images.githubusercontent.com/37565512/37633909-97dbf45e-2c37-11e8-9893-17c3f094c17c.png)

how do I see win rates?

**Comment by Deckweiss** [comment]
Having the same issue.

Overlay in game works partially:
- doesn't show deck name
- doesn't show win rate
- doesn't show chances of drawing
- only shows cards seen this match, not persistent
- tried all the F shortcuts, F1 and F2 work, the rest doesnt change anything

**Comment by vanish2k** [comment]
That's the issue with 1.0.75 version. We should wait untill developer fixes that.

**Comment by extesy** [comment]
Try `1.0.76`.
