### ISSUE TITLE
Import problem - x.x.75

### ISSUE THREAD

**Issue by Krapulax80** [extesy/DeckTracker#195]
Hi,

1. After latest TES:Legends update (Morrowind) I started to have errors 1.0.74 version of UDT. 
2. I updated UDT to 1.0.75 - error disappeared but the import/export button was still not working.
3. I red on forum Access 2016 runtime should be installed - however that one is not compatible with my Office 365 C2R installation.
4. Further research showed me Access 2013 runtime is similar to 2016 and should work even when C2R office is installed.
5. After installation sadly the import still does not work. (it gives "invalid line format ..."  - ... is a new set card - errors)
Export seemingly working - but Import is not.

# How to report a bug

1. Deck tracker does not work for you at all? There is an [existing issue](https://github.com/extesy/decktracker/issues/21) for this. Look [over there](https://github.com/extesy/decktracker/issues/21), do not create a new issue.
2. Does it crash? Provide a full exception message or a screenshot and what _exactly_ did you do right before that.
3. Some specific feature doesn't work as expected? Read a [reporting problems](https://github.com/extesy/DeckTracker#reporting-problems) section and provide debug logs.

In all cases, please provide a detailed step-by-step instructions on how to reproduce your issue. Nobody except you knows specifics of your computer and software you running on it. The less details you provide, the smaller is the chance that your report will be properly investigated.

![image](https://user-images.githubusercontent.com/37410363/38418163-328ee1ce-3993-11e8-9f3f-d62e50670f6b.png)

**Comment by DeathofSouls** [comment]
+1 I’m having this same issue, but for me it does not allow me to export or import.  when I try and export my collection it doesn’t give me an error, however when I look on the website the new expansion (Morrowind) cards are not accounted for.

**Comment by extesy** [comment]
Try `1.0.76`.
