### ISSUE TITLE
No longer importing or exporting

### ISSUE THREAD

**Issue by rinks361** [extesy/DeckTracker#198]
Using 1.0.75 and the latest update to the game causes the deck tracker to run into errors.

**Comment by vanish2k** [comment]
After tracker launch and deck import attempt try to do any action ingame first, for ex. go in decks menu and back on main screen. Then you should be able to import ur deck w/o problems or errors.

**Comment by SolarEclipz** [comment]
Thank you @vanish2k doing this worked for me for the time being.

**Comment by extesy** [comment]
Try `1.0.76`.
