### ISSUE TITLE
Decks are not being pulled after timeout disconnect and re-login

### ISSUE THREAD

**Issue by Aravane** [extesy/DeckTracker#2]
Version: 1.0.8

Issue: the tracker can't "find" any decks, similar in effect/functionality to the issue I reported on reddit back on 1.0.3. Restarting the tracker doesn't fix the issue.

Reproduction?: the issue reappeared after I lost my connection mid-game (it was a Draft match). The game asked me to re-log, and after I did (and resumed my game) the tracker could no longer "see" my decks (checked with F5, no response). I can't remember whether this occurred when I was done with my Draft and moved on to a Gauntlet match, or already during the resumed Draft itself.

Solution: restart the game (and maybe the tracker? since I did that first).

**Comment by extesy** [comment]
Disconnect/reconnect issues are extremely hard to debug and fix because the game protocol in these cases is quite different. I will try to fix those cases but since it's so hard I will first focus on easier issues with more value.

**Comment by extesy** [comment]
@Aravane I've made some improvements recently to this. Can you please let me know next time you have to reconnect if it works better now.

**Comment by Aravane** [comment]
Sure, I'll let you know.

**Comment by Aravane** [comment]
Issue appeared again today (why you close this?).

Version v1.0.15
Issue: the tracker can't "find" any decks, similar in effect/functionality to the issue I reported on reddit back on 1.0.3. Restarting the tracker doesn't fix the issue - the game needs to be restarted.
Reproduction: the disconnect occurred while in a victory screen after a draft game (I had left it idling). When I returned and relogged the tracker no longer worked.

**Comment by extesy** [comment]
I closed this issue because there was no evidence of it happening for 7 days and I didn't want leaving the bug open forever just in case it could happen again. That's what "reopen" button is for. So now it's open again. I've renamed the issue to emphasize that it only happens after reconnect.

**Comment by extesy** [comment]
@Aravane Have you noticed any changes recently, positive or negative? Does reconnect still cause the tracker to stop working completely?

**Comment by extesy** [comment]
Closing until it happens again...
