### ISSUE TITLE
3 Color Decks Don't Import

### ISSUE THREAD

**Issue by lordexorr** [extesy/DeckTracker#202]
Error "Too many card colors in deck: 3".

Anyone else seeing this?

**Comment by Krapulax80** [comment]
I think we all seeing it :(

**Comment by Pierodel10** [comment]
+1

**Comment by CerberoCdT** [comment]
+1

**Comment by Wedmer** [comment]
[This is checked here](https://github.com/extesy/DeckTracker/blob/5172c10bfdd910ea4f50444456e2149082aa3992/DeckTracker/Domain/ArchetypeManager.cs#L181)

**Comment by Pierodel10** [comment]
Wedmer, excuse me, but what does that mean?

**Comment by lordexorr** [comment]
That’s the line of code in the script causing the error. I’m unsure if there’s more that would need to be altered in the script other than that though.

**Comment by Wedmer** [comment]
I've not found  maximum colour count check elsewhere. Only [selector](https://github.com/extesy/DeckTracker/blob/37a1379675fe994eb3cf0197b921888bb0163de9/DeckTracker.Common/decktypes.txt#L65)

**Comment by extesy** [comment]
Fixed in `1.0.76`.
