### ISSUE TITLE
Repository out of date

### ISSUE THREAD

**Issue by Randactyl** [extesy/DeckTracker#204]
Hey, thanks for the updates just now!

I was wondering if you could push your changes to the repo. Right now, the code is still from release 1.0.69.

**Comment by extesy** [comment]
Updated: d30a4d7a860f3ff7682328af50e3ab5b8844f646

**Comment by Randactyl** [comment]
Great, thanks!

**Comment by Randactyl** [comment]
So I still can't run from source.

I've attached some files. [rel_events.log](https://github.com/extesy/DeckTracker/files/1911518/rel_events.log) is from the released version. [src_events.log](https://github.com/extesy/DeckTracker/files/1911519/src_events.log) and [src_error.log](https://github.com/extesy/DeckTracker/files/1911517/src_error.log) are from the latest available source.

Looking at the recent commits, this makes sense. Very little code was changed, mostly new log messages and nuget/SDK target updates.

Is there any way you could push all of the changes, please?
