### ISSUE TITLE
Access denied after unable to copy to clipboard

### ISSUE THREAD

**Issue by LordUber** [extesy/DeckTracker#216]
I had an issue where I could not copy to the clipboard (after working an impot once successfully). Then after a reinstall, I got an access violation. Another reinstall x2 still has this problem, Any ideas? Is a fix required?

Windows 10, zonealarm AV

**Comment by extesy** [comment]
Duplicate of #129

**Comment by LordUber** [comment]
The problem was my antivirus and firewall, Zonealarm. Disabling it temporarily fixed the problem.

**Comment by extesy** [comment]
Thanks for the follow up. Unfortunately it's impossible to detect which application blocks the keyboard from the deck tracker.
