### ISSUE TITLE
Unable to export to Legends-decks.com

### ISSUE THREAD

**Issue by BigBullTrout** [extesy/DeckTracker#218]
Hello,

I have upgraded to the latest universal deck tracker and can not import decks or export full collection. These buttons are greyed out. Any suggestions on how to fix this? I am wanting to use legends-decks.com. I have tried closing the tracker and restarting, as well as restarting the computer. I always start the tracker before opening up The Elder Scrolls Legends and it will track games, just not allow use of deck import and export collection.

Thanks

**Comment by Pizzabh** [comment]
Hey,

I also have this problem.  Tried using it in TESL, recognize text says Edler Scrolls Legends in blue, then blinks sometimes to red. Buttons are always greyed out despite multiple restarts etc. No report file created.

Thanks.

**Comment by Pizzabh** [comment]
After debugging and identifying the problem and scouring the threads for the same issue the problem was fixed by installing Access Runtime 2016.
