### ISSUE TITLE
Dual Display option

### ISSUE THREAD

**Issue by Razviar** [extesy/DeckTracker#219]
Hi! Many users of our website teslegends.pro who actively use DeckTracker are using 2 or more displays connected to their PC. So they are asking about enabling multi-display dragging for overlay window, so user could drag overlay away from game screen to another display.

As I see this problem, it would be great if there were an option to show deck not in the in-game overlay but in separate window, ready to be dragged on second display. If it's not too hard to implement, please take into conciderayion this feature request.

**Comment by extesy** [comment]
Unfortunately that would require rewriting most of deck tracker logic pretty much from scratch. Out of scope for now.
