### ISSUE TITLE
installation has failed 

### ISSUE THREAD

**Issue by tesldecktracker** [extesy/DeckTracker#221]
heyy,

i have had it working in the past on my computer, but recently it wasn't working anymore for me so i decided to download the latest version. when i open the "UniversalDeckTracker.exe" i get an error message saying: 
"installation has failed.
There was an error while installing the application. check the setup log for more information and contact the author"

setup log is included.

i looked through the issues and didn't see this issue was reported or solved somewhere yet, my apologies if i mist it. 

what ca i do? thanks in advance. 

[SquirrelSetup.log](https://github.com/extesy/DeckTracker/files/2042490/SquirrelSetup.log)

**Comment by extesy** [comment]
@tesldecktracker Close your game and deck tracker, both of them. If that doesn't help then reboot your computer and retry.
