### ISSUE TITLE
[Eternal] entomb causing extra copies?

### ISSUE THREAD

**Issue by waitthisisntmtg** [extesy/DeckTracker#3]
Hey Ex,

I was doing some gauntlet testing and the opp played 2 ob golem, but as you can see in the screenshot, once I killed them it changed it to saying there were 4 golems and 2 of the equipment they put out, not sure why. Let me know if you need more from me!

![image](https://cloud.githubusercontent.com/assets/28144402/25655352/949da9ee-2fc2-11e7-85ea-6f05a347a1d4.png)

**Comment by extesy** [comment]
Thanks for the report. This is enough information for now. I'll take a look. With the opponent decks it's a known issue that the tracker can't differentiate cards played from hand and cards created by some other cards. This issue might be related.

**Comment by extesy** [comment]
@waitthisisntmtg Try version 1.0.9 and let me know if you still see this problem.
