### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by Saiyan** [extesy/DeckTracker#31]
So I wanted to look inside the tools code before I install something that so many AV Suites identify as a virus,
Will you ever publish your code so we could build the DeckTracker ourselfs or do we always have to rely on you that there will be no malicious stuff in your .exe blobs?

**Comment by extesy** [comment]
See #22. Builds starting with `1.0.41` are not identified as virus by any systems.

**Comment by extesy** [comment]
It would be a fairly stupid idea to create a best available deck tracker for the sole reason of distributing malware to a tiny group of people who play two card games, isn't it? You don't need to trust it, I'm not trying to please everybody, this is a free tool after all. Just try to apply some logic.

**Comment by Saiyan** [comment]
I really do not mean to upset or annoy you but logic has nothing to do with this.
It's a matter of security if I install some tool someone else built and that I know nothing about but what the developer tells me.
I'am just thinking that publishing the code would be in the best interest of everybody but if you want to keep the source closed thats fine, thank you.
