### ISSUE TITLE
"Only works when game client is running and fully initialized" error

### ISSUE THREAD

**Issue by crunchyfrostedflakes** [extesy/DeckTracker#32]
![deck_tracker](https://user-images.githubusercontent.com/29633587/27443557-7229ca86-5741-11e7-9dc7-7e68d3314b34.png)

Trying to import full collection on Elder Scrolls: Legends, but nothing works. Program doesn't do anything. Doesn't track my decks, cards, when playing game either.

**Comment by extesy** [comment]
You seem to have the same symptoms as a few people in ticket #5. Let's not fork discussion and continue there.
