### ISSUE TITLE
Crash report data

### ISSUE THREAD

**Issue by bedulis** [extesy/DeckTracker#37]
I have crash report data that DeckTracker wants me to send 
the developer. I'll attach it.

[crash.dmp.txt](https://github.com/extesy/DeckTracker/files/1100243/crash.dmp.txt)
[error.log.txt](https://github.com/extesy/DeckTracker/files/1100244/error.log.txt)

**Comment by extesy** [comment]
@bedulis Can you please report errors using https://github.com/extesy/DeckTracker#reporting-problems instructions? Unfortunately I am unable to investigate game crash dumps.
