### ISSUE TITLE
Massive Overlay

### ISSUE THREAD

**Issue by banzify** [extesy/DeckTracker#38]
I can't reproduce this as I don't know how it happened. 
My opponents deck contents as they become listed are massively oversized.
Is there a configuration folder I can edit/delete to fix the issue? I didn't run any installer, just the standalone .exe  
Here is a photo for reference. 
<img>http://i.imgur.com/Rcx2j3A.jpg</img>

**Comment by extesy** [comment]
@banzify Drag the bottom-right corner of the deck list to resize it, see https://github.com/extesy/DeckTracker#faq-frequently-asked-questions

**Comment by banzify** [comment]
Thank you!
