### ISSUE TITLE
Stone Cudgel Counted as Card in Opponent's Deck

### ISSUE THREAD

**Issue by sjspero** [extesy/DeckTracker#4]
i suppose it's due to it being spawned in their void

**Comment by extesy** [comment]
@sjspero It's hard for me to reproduce since I don't own any `Statuary Maidens` yet. Does `Stone Cudgel` appear in addition to all other opponent's cards or does it replace the card of the unit that died?

**Comment by extesy** [comment]
@sjspero I've made some adjustments in the latest version. Can you please check if `Stone Cudgels` don't count as cards anymore for the opponent?
