### ISSUE TITLE
 TESL collection export not working properly

### ISSUE THREAD

**Issue by wulnoot** [extesy/DeckTracker#40]
when I export, most of the time it doesn't copy my entire collection. cuts off like halfway through. and when it does copy all the way to Odahviing I can tell it's missing cards because legends-decks tells me I need 150 soul gems for the brynjolf deck even though I got it for free

**Comment by extesy** [comment]
@wulnoot so it doesn't export new HoS cards but it does export all older cards?

**Comment by wulnoot** [comment]
@extesy no that's not the issue, been experiencing it since before HoS patch. Basically only half the collection gets copied to clipboard and the last card that does get copied is cut off e.g. "Her" when the next card should be Heroic Rebirth. Sometimes it does seem to copy properly; Odahviing (the last card in the collection that I own) will show up at the end of the list, but several other cards that I own aren't copied - specifically Sightless Skulk and Move in Shadows but there could be more

**Comment by extesy** [comment]
@wulnoot I'm working with legends-decks developer to fix the problem, should be working soon. In the meantime please update to `1.0.48` version.
