### ISSUE TITLE
Closing window does not kill process and prevents reinstallation.

### ISSUE THREAD

**Issue by MatthewTighe** [extesy/DeckTracker#41]
I closed the main window displaying stats because I was done with the tool, but some background process (which could use a better name so I can actually kill it) continued to run such that the deck tracking overlays continued during my matches. No obvious way to reopen main window, because the desktop shortcut referenced a program that no longer existed. Tried reinstalling.

Logs from reinstallation failure: https://pastebin.com/BJGUETae

Contents of Users/<me>/AppData/Local/UniversalDeckTracker/version:
DeckTracker.InGame.dll
DeckTracker.InGame.Helper.dll

Windows 10
Deck Tracker version 1.0.47
Using it for Elder Scrolls Legends collection export feature

**Comment by extesy** [comment]
@MatthewTighe You also have to close the game process because the game uses one of dlls from the deck tracker.
