### ISSUE TITLE
BUG: my deck list is stuck 

### ISSUE THREAD

**Issue by mrworld86** [extesy/DeckTracker#42]
it seems that my deck list is stuck in the upper left-hand corner showing just a little bit of it. i am unable to move it so i cannot see my deck. Could i get some help for this?
![universal deck track failure](https://user-images.githubusercontent.com/29776096/27686483-f4ad7d18-5ca0-11e7-832c-accba283848a.png)

Jeff

**Comment by extesy** [comment]
@mrworld86 Please close both game and deck tracker then delete `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\config.json` file. After that you can start deck tracker and the game again.
