### ISSUE TITLE
Export Full Collection parsing error

### ISSUE THREAD

**Issue by VforValens** [extesy/DeckTracker#43]
events.log shows

`2017-06-30T05:48:40.3355040Z|TheElderScrollsLegends|Debug|Injection state changed: Injecting
`

immediate CTD upon opening the file. Have added exceptions in Avira for both process, the shortcut, and the folder location in AppData/Local

**Comment by VforValens** [comment]
Running as administrator fixed...odd but ok...but now getting

'Something went wrong...
Unexpected character encountered while parsing value: P Path ", line 0, position 0.

**Comment by neuroaktivo** [comment]
2 things can happen when importing full collection:

_Something went wrong...
Unexpected character encountered while parsing value: P Path ", line 0, position 0._

or when u get the string and hit "Import collection":

_Oops!

There was an error in your collection and it cannot be saved. If the problem persists please contact an admin._

I can't import full collection to legends-decks right now. Hope you are able to fix this and thanks for this awesome tool.

**Comment by extesy** [comment]
@neuroaktivo Please wait until the game loads completely reaches the main menu (including closing all popup messages and daily quest notifications).
