### ISSUE TITLE
does not want to connect to ESL

### ISSUE THREAD

**Issue by waitthisisntmtg** [extesy/DeckTracker#46]
Hey Ex,

I had this working last night on 1.48 but now 1.49 just doesnt seem to turn up when i start the game. I have restarted game and tracker multiple times to no avail. Wont let me import, export or track games.

Let me know if theres something I can give you to help with this.

Thanks!

**Comment by extesy** [comment]
@waitthisisntmtg Can you please provide debug logs according to https://github.com/extesy/decktracker/#reporting-problems?

**Comment by extesy** [comment]
@waitthisisntmtg Is this still happening? My metrics show thousands of games per day using the tracker, so it's not a global problem.

**Comment by waitthisisntmtg** [comment]
All good now!
