### ISSUE TITLE
[New Feature] Move ui to second screen

### ISSUE THREAD

**Issue by wirsmann** [extesy/DeckTracker#47]
If you have dual monitors could you put the deck trackers on the second screen so it doesn't cover the game at all?

**Comment by extesy** [comment]
@wirsmann Unfortunately it's not possible because the deck list is not a separate overlay which can be moved. It's displayed as part of the game UI, in the same window as a game itself. So unless the game supports multi-monitor rendering, it's not possible to show anything outside of its window.
