### ISSUE TITLE
Cant use DeckTracker

### ISSUE THREAD

**Issue by N00btuber** [extesy/DeckTracker#49]
Hey
I've installed the latest version 1.0.50 but it wont work for me.
I want to export my TES Legends collection and they game gets detected, but I cant do anything with DeckTracker (I waited till TES Legends was fully loaded, even played 2 games, but still nothing happened)

When I try to click Import/Export it just shows "Only works when game client is running and fully initialized"
Help would be great, thanks in advance

![decktracker bug](https://user-images.githubusercontent.com/29862311/27792105-6cbd9752-5ff8-11e7-9b30-3837776009f3.JPG)

**Comment by extesy** [comment]
Looks like the same problem as in #5. Let's continue the investigation there. I'll close this ticket to avoid forking the thread.
