### ISSUE TITLE
List of cards ocupy 1/3 of the screen

### ISSUE THREAD

**Issue by GranJoseto** [extesy/DeckTracker#52]
Hi, first of all: great work, I love it!!!
I just wanted to report that the list of my cards ocupy 1/3 of the screen since a couple of days... I don't know what to do or how it happened. I tried to "re-install" (downloaded again and reexucuted actually), but all my decks were still there and sadly also the 1/3 screen thing.
Thanks

**Comment by extesy** [comment]
@GranJoseto you can resize the deck list, see FAQ on this page: https://github.com/extesy/decktracker/#faq-frequently-asked-questions
