### ISSUE TITLE
Decklist not showing up

### ISSUE THREAD

**Issue by Sabamonster** [extesy/DeckTracker#54]
After a day or so of playing, Neither my own, or my opponents decklist shows up anymore.

**Comment by kmelkon** [comment]
Same thing happens to me, even though it shows the game is running in red.
I'd like to point out that I've used this with Eternal before and it worked fine and I did uncheck Eternal in the game mode menu.

**Comment by extesy** [comment]
Looks like the same problem as in #5. Let's continue the investigation there. I'll close this ticket to avoid forking the thread.
