### ISSUE TITLE
Aela's Huntmate on deck import (perhaps issue with ' in cards, generally)

### ISSUE THREAD

**Issue by joeymavity** [extesy/DeckTracker#57]
I've noticed a few times when importing a deck that Aela's Huntmate doesn't get added to the deck list inside TESL. I think this may be a problem with apostrophe's in general not being escaped properly in the import function, but I haven't tested extensively.

**Comment by joeymavity** [comment]
Follow-up: I also tested "Ancestor's Battleaxe" and "Ulfric's Zealot" and they imported fine, so it may just be an issue with Aela's Huntmate. If you're looking for a test import deck, here's one:

`###Aela's companions (modified)###
3 Fiery Imp (Set1 #1821)
3 Rapid Shot (Set1 #1757)
3 Afflicted Alit (Set1 #1290)
3 Circle Initiate (Set3 #2150)
1 Orc Clan Captain (Set1 #1131)
3 Shield Breaker (Set3 #2088)
3 Wind Keep Spellsword (Set1 #1567)
3 Companion Harbinger (Set3 #2217)
3 Crushing Blow (Set1 #1461)
3 Grim Shield-Brother (Set3 #2136)
3 Morkul Gatekeeper (Set1 #1105)
3 Aela's Huntmate (Set3 #2133)
1 Garnag, Dark Adherent (Set2 #2021)
3 Ulfric's Zealot (Set3 #2193)
3 Shadowfen Priest (Set1 #1526)
3 Sower of Revenge (Set999 #1807)
2 Child of Hircine (Set1 #1269)
2 Triumphant Jarl (Set1 #1183)
1 Aela the Huntress (Set3 #1712)
1 Ancestor's Battleaxe (Set3 #2185)
`

**Comment by extesy** [comment]
Thanks for report, @joeymavity! I'll check this when I get back from vacation in a few days. It might be a bug either on my side or on legends-decks side. Either way, we'll figure it out.

**Comment by extesy** [comment]
Fixed in version `1.0.53`.
