### ISSUE TITLE
Tracker doesn't recognize game

### ISSUE THREAD

**Issue by cynicalrage** [extesy/DeckTracker#58]
I launch Universal Deck Tracker and it won't recognize ESL Legends, it always writes in red in the top right

Running Game Detected: TheElderScrollsLegends in red. im assuming i have done something wrong. 

I run the tracker before i launch the game also like stated.

**Comment by extesy** [comment]
Looks like the same problem as in #5. Let's continue the investigation there. I'll close this ticket to avoid forking the thread.
