### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by Slowbad** [extesy/DeckTracker#60]
I may be mistaken but I thought you were supposed to share the source code for programs you distribute under the GPL license. I say this because I want to see what you have going on here and see if I can contribute. Where are you actually hosting this?

**Comment by extesy** [comment]
@Slowbad You are mistaken. You are only supposed to do that when you *use* GPL software. This does not apply to privately developed software that does not use any GPL components.

**Comment by Slowbad** [comment]
@extesy Is this tracker covered under any open source license? If not, why not make this tracker open source?

**Comment by extesy** [comment]
@Slowbad I am the author so I choose whatever license I want for it and I am free to change the license at any time. Currently the source code is not published so the only implicit license is that nobody who steals it can do anything with it. Once it is published, I will pick a license.

**Comment by Slowbad** [comment]
@extesy Thank you for taking the time to answer me. I look forward to if and when you open source this project.
