### ISSUE TITLE
Oni Ronin from Shogun's Scepter reduce actual Oni Ronin count

### ISSUE THREAD

**Issue by emerald000** [extesy/DeckTracker#62]
I have a deck with 4 Oni Ronin and Shogun's Scepters. After playing 2 Oni Ronin and 2 Shogun's Scepters in a game, the tracker was saying I had 0 Oni Ronin left (actually had 2). It looks like it counts the generated Oni Ronin as a card from your deck and modifies the deck list.

**Comment by extesy** [comment]
@emerald000 which version of deck tracker were you using?

**Comment by emerald000** [comment]
I was using the latest version at the time, I'm guessing 1.0.53.

**Comment by extesy** [comment]
Fixed in `1.0.55`.
