### ISSUE TITLE
TES Legends crashes

### ISSUE THREAD

**Issue by exlibris1982** [extesy/DeckTracker#64]
I've just installed the tracker and the game gets sluggish and freezes a lot (have to close game and reopen to reconnect).
I play the game windowed, is that what causes this?

I really want to use it but been losing games due to missing a complete turn while reconnecting.
Can you help please?

**Comment by extesy** [comment]
@exlibris1982 I don't know if that is the reason, nobody has reported this before. Have you _tried_ confirming your theory and playing full screen? As you can guess, it's much easier for you to experiment on your own machine than for me to do the same.

**Comment by exlibris1982** [comment]
Still doesn't work.
Full screen and still crashes and slows down computer.

**Comment by extesy** [comment]
@exlibris1982 Then your computer is probably just too slow for this at the moment. Ticket #21 is tracking the performance improvement work.

**Comment by exlibris1982** [comment]
If it was just slow I could understand.
But crashes. I'm just trying to give you feedback.

How much processor can a tracker use? I doubt it'll slow anything down.

Anyway, cheers man.

On Jul 13, 2017 11:47 PM, "Oleg Anashkin" <notifications@github.com> wrote:

@exlibris1982 <https://github.com/exlibris1982> Then your computer is
probably just too slow for this at the moment. Ticket #21
<https://github.com/extesy/DeckTracker/issues/21> is tracking the
performance improvement work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/extesy/DeckTracker/issues/64#issuecomment-315222445>,
or mute the thread

**Comment by extesy** [comment]
It paints 2D overlay on top of 3D playmat. Depending on CPU and video card and video drivers it can consume less or more resources. I only have one computer to test on and there are 1000+ deck tracker users with all kinds of hardware.

**Comment by exlibris1982** [comment]
If you are on top of the issue, keep up the good work then.
Probably in a future version it'll work for me. But it's very useful.

Cheers.
