### ISSUE TITLE
Problem with symantec

### ISSUE THREAD

**Issue by Onirisaslan** [extesy/DeckTracker#65]
The Deck Tracker is untrustworthy according to Symantec and won't let me install it. Is there a way to avoid this problem. (Already tried to disable Symantec but it does not work). Thanks

**Comment by extesy** [comment]
@Onirisaslan If you disabled Symantec but Symantec doesn't let you install Deck Tracker - that means you haven't disabled Symantec. Please read https://github.com/extesy/DeckTracker#known-issues for guidelines.
