### ISSUE TITLE
DeckTracker won't open.

### ISSUE THREAD

**Issue by turnageb** [extesy/DeckTracker#66]
I've been having problems in that the tracker won't open at all. It worked previously, and to my knowledge I didn't change any settings on my computer before it stopped working. Since then I have uninstalled, re-downloaded the app, installed it, and added it as an exception to Windows Defender. It still won't open when I try to launch the program.

**Comment by extesy** [comment]
@turnageb Please follow https://github.com/extesy/DeckTracker#reporting-problems instructions and provide debug logs.

**Comment by turnageb** [comment]
I don't understand these instructions. Please clarify for my not tech savvy self.

**Comment by extesy** [comment]
@turnageb Please navigate to `C:\Users\{profile}\AppData\Local\UniversalDeckTracker\1.0.54` folder and launch `UniversalDeckTracker.exe` from that folder manually.

**Comment by turnageb** [comment]
I tried but again, nothing happens.

**Comment by extesy** [comment]
I'm sorry but I don't know what went wrong on your machine. I don't know how to do tech support over internet.
