### ISSUE TITLE
overall win rate

### ISSUE THREAD

**Issue by waitthisisntmtg** [extesy/DeckTracker#7]
Hey Ex,

It would be sweet to not only see win rates by deck, but also total win rates.

Also, idk if this is possible at all, but separating gauntlet, ranked, and draft games would be cool too.

Thanks for all the awesome work you're doing!!

**Comment by extesy** [comment]
@waitthisisntmtg Yes, it's a great idea and I will definitely add this. For forge or draft decks it already happens - all forge/draft runs are bundled into a single deck entry, you should see "Draft Deck" and "Forge Deck" in the left list. But for gauntlet/ranked you pick your own constructed deck so the separation between AI and human games would be useful.

**Comment by extesy** [comment]
Both of these features are now available in version 1.0.16.

**Comment by waitthisisntmtg** [comment]
That's awesome! Sick work man.
