### ISSUE TITLE
Save Eternal config

### ISSUE THREAD

**Issue by Asbra** [extesy/DeckTracker#70]
Currently it does not seem to save window sizes/positions for Eternal, nothing is added to config.json when closing game, and ESL seems to overwrite any additions.
I added the name "Eternal" with values copied from ESL to the config. This was removed after running ESL (assuming it's after ESL saves settings)

**Comment by extesy** [comment]
@Asbra It does support both games at the same time. Sample config:
```
{"Eternal":{"isVisible":true,"isPlayerDeckVisible":true,"isOpponentDeckVisible":true,"isTestDeckVisible":true,"isRankVisible":true,"testDeckIndex":13,"playerDeckX":2260,"playerDeckY":150,"playerDeckScale":1,"opponentDeckX":32,"opponentDeckY":182,"opponentDeckScale":1,"testDeckX":2219,"testDeckY":88,"testDeckScale":1,"isWinRateVisible":true,"isDynamicPlayerDeck":false,"isProbabilitiesVisible":true},"TheElderScrollsLegends":{"isVisible":true,"isPlayerDeckVisible":true,"isOpponentDeckVisible":true,"isTestDeckVisible":false,"isWinRateVisible":true,"testDeckIndex":1,"playerDeckX":2260,"playerDeckY":150,"playerDeckScale":1,"opponentDeckX":50,"opponentDeckY":150,"opponentDeckScale":1,"testDeckX":2260,"testDeckY":150,"testDeckScale":1,"isRankVisible":true,"isDynamicPlayerDeck":true,"isProbabilitiesVisible":true,"isZeroCardCountsVisible":true}}
```

**Comment by Asbra** [comment]
That's a bit of a bummer. Hope this will be improved in the future so that it can truly be a universal tracker.

**Comment by extesy** [comment]
@Asbra Sorry, I don't understand. What I was saying is that both games should work just fine and configs for them are tracked independently. Try copy/pasting my sample config into your `config.json` file.

**Comment by Asbra** [comment]
@extesy Sorry, read your post wrong. Works fine!
Played a couple matches in each game and checked that config saves/loads fine.

Must've done something wrong previously, I tried manually (copied the pair TheElderScrollsLegends as Eternal and saved) but it got overwritten with only TESL config again at some point.
