### ISSUE TITLE
не видит игру

### ISSUE THREAD

**Issue by YurijLL** [extesy/DeckTracker#78]
Я почему подумал, что с русской версией не работает, потому что не видел твой трекер игру. ТОчнее так, в теле трекера он писал красным, что видит игру, однако в самой игре ничего не появлялось и в трекере ничего не было. Оказалось ситуация такая, еслия запускаю игру с ярлыка, то все нормально, в игре есть колоды и игры видны в трекере, а если я выхожу из игры, но лаунчер не закрываю, я обычно так и делаю, а потом запускаю игру из лаунчера, то тогда трекер ничего не делает, только надпись ту пишет и все.
И еще, колоды оппонента не сохраняются?

**Comment by extesy** [comment]
@YurijLL This is a known issue, duplicate of #5. Please clarify that you mean by "колоды оппонента не сохраняются".
