### ISSUE TITLE
[Feature] Overlay customisation

### ISSUE THREAD

**Issue by VitaliyKulikov** [extesy/DeckTracker#79]
It will be nice to have font (overlay) size scalability.

I think it will be enough just [+] / [-] mini buttons (independently for window) those represent +-25% increase / decrease

I just found that opponent's deck list overlay is too big for me ))

**Comment by extesy** [comment]
@VitaliyKulikov You can resize the deck list, see https://github.com/extesy/DeckTracker#faq-frequently-asked-questions. All other customizations will be part of #27.

**Comment by VitaliyKulikov** [comment]
@extesy thanks a lot.
