### ISSUE TITLE
[security] Avira find 'TR/Agent.eomea'

### ISSUE THREAD

**Issue by SylvainNeau** [extesy/DeckTracker#82]
Hi,
With your last release, Avira find some 'TR/Agent.eomea' menace.
![image](https://user-images.githubusercontent.com/10066492/28279403-ab610132-6b20-11e7-86c2-493dc5e01c5d.png)

**Comment by extesy** [comment]
Known issue, it's a false positive, see FAQ.

**Comment by extesy** [comment]
@SylvainNeau Release `1.0.57` does not trigger any warnings anymore.
