### ISSUE TITLE
Deck overlay doesn't show anything

### ISSUE THREAD

**Issue by neuroaktivo** [extesy/DeckTracker#86]
![image](https://user-images.githubusercontent.com/18504238/28429689-dfc334fe-6d7d-11e7-9c6a-f6a19800b36c.png)

This just started happening some days ago, i have redownloaded and reinstalled, still the same.

**Comment by extesy** [comment]
@neuroaktivo Press F1, see https://github.com/extesy/decktracker/#keyboard-shortcuts

**Comment by neuroaktivo** [comment]
please look at screenshot its not that i dont know the hotkeys.

**Comment by extesy** [comment]
I don't see any box at the left. I only see the label in the bottom-right corner. Please press F2 key while playing the game. Try also deleting `config.json` file.

**Comment by neuroaktivo** [comment]
its semitransparent:
![image](https://user-images.githubusercontent.com/18504238/28436379-0e172658-6d97-11e7-9165-05b59bbb5582.png)

**Comment by extesy** [comment]
I have no idea what's that. Does it disappear when you press F1? Also try removing config file as I have already suggested above.

**Comment by neuroaktivo** [comment]
yes it does, i believe its the box where the decklist should appear, enemy played cards do appear:
![image](https://user-images.githubusercontent.com/18504238/28443633-af316dc6-6db7-11e7-8729-46b1209b192b.png)
I tried deleteing UniversalDeckTracker.exe.config.xml but it did nothing either.

**Comment by extesy** [comment]
Config file: `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\config.json`

**Comment by neuroaktivo** [comment]
I found the problem, the "playerDeckScale" value was set to a negative(changes it to 1 and it fixed the problem). So look into the code that sets that value cause theres some edge case or something that can set it to a negative. Seeya and thanks for the help!!

**Comment by extesy** [comment]
Cool, thanks for finding the problem! I don't really understand how it's possible to set it to a negative value, but I'll make sure to put a protection against that in the code.
