### ISSUE TITLE
The Buttons are gray

### ISSUE THREAD

**Issue by Zoli3** [extesy/DeckTracker#87]
I want to export my whole cards (TESL) to the www.legends-decks.com site.
I downloaded the UniversalDeckTracker.exe v1.0.58 (2.92 MB) and i launched this with the game. I press ALT+TAB and i can't press any button on the tracker. Just describe: running game detected: TESL
and the buttons (import deck and export full collection (what i want)) are grey.

What I've done:
I tried the v1.0.57, but still didnt work.
Disable the Antivirus.
I wait 10 second after red.
Run the UDT as administrator.
I lanched first the UDT than TELS. Not work. I launched first the TESL, than UDT. Not work.
My C:\Users\XXX\AppData\Roaming\UniversalDeckTracker is empty. Empty when i launched the UDT and empty when i'm in the game. And empty after i quit.
I only launched the game with the Bethesda Launcher, not Steam.
WIN7 64bit
I'm always online in the www.legends-decks.com

How can i export my cards to the website?
I really hope you can help me.

**Comment by extesy** [comment]
Hi @Zoli3, these symptoms seem to match existing issue #5 so I'm closing this ticket to avoid forking the discussion.

**Comment by Zoli3** [comment]
OKE. But i dont have WIN10 and Bitdefender. So i dont find the solution in mnefstead's comment.
Any Idea?
