### ISSUE TITLE
Story mode doesn't show entire deck

### ISSUE THREAD

**Issue by TouchMe-Sama** [extesy/DeckTracker#92]
That's literally the problem, I don't see a tutorial or anything to help me use this a little bit better, i don't even know if it's supposed to be like this. Tried to find tutorials on YouTube and ask info in twitter, no one had a clue or answered me. Here is a screenshot: 

![sem titulo](https://user-images.githubusercontent.com/30402860/28513067-04632e5e-702b-11e7-89b4-7eb3a3445a54.png)

I don't know if I submited the image correctly. Anyway, thanks.

Oh, I have seen now that this is a known issue. But it doesn't tell me how to solve it. Anything I can do?

**Comment by extesy** [comment]
@TouchMe-Sama It's in the https://github.com/extesy/DeckTracker#known-issues list. Have you started the tracker before the game?

**Comment by TouchMe-Sama** [comment]
I did...

**Comment by extesy** [comment]
@TouchMe-Sama What game mode does this happen in? Please list game modes you've tried with this bug and game modes you've tried without this bug.

**Comment by TouchMe-Sama** [comment]
Story mode is where the bug is at. Play mode is just fine. Not the biggest of a problem if you ask me, but since I just started TESL yesterday, I thought it was bugging in all the modes. I hadn't tested Play mode at the time, not until you asked me. 
Thank you again!

**Comment by extesy** [comment]
I have never tested story mode. I will take a look.

**Comment by extesy** [comment]
Fixed in `1.0.59`.
