### ISSUE TITLE
SQLiteException causes random issues like disappearing cards or missing card text

### ISSUE THREAD

**Issue by extesy** [extesy/DeckTracker#96]
I saw this on https://www.twitch.tv/iamcvh stream and this required restarting the game. If anyone can please confirm if it ever happened to them that would be very helpful.

**Comment by VitaliyKulikov** [comment]
confirm #97

**Comment by VitaliyKulikov** [comment]
here some screenshots: 
- no text on cards ![no text](https://steamuserimages-a.akamaihd.net/ugc/868484760330623856/E9B41415593381043FE582360D5CA359574BE4AD/)
- animation freeze ![freeze](https://steamuserimages-a.akamaihd.net/ugc/868484760330623409/DDB5A00AE45CF8742761BC219D71F02EFCD65529/)
- repeatable exeption in ``error.log``
``` c#
dwd.core.sqlite.SQLiteException: Unable to bind parameter com.direwolfdigital.hydra.rules.entities.playhistoryentry.name at 2. SQLite Error Misuse
  at dwd.core.sqlite.SimpleSQLiteCommand.BindParameter (IntPtr stmt, Int32 index, System.String value) [0x00000] in <filename unknown>:0 
  at dwd.core.sqlite.SimpleSQLiteCommand.AddArgument (System.String arg) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.TryLocalize (System.String key, System.String& value, System.Object[] args) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.Localize (System.String key, System.Object[] args) [0x00000] in <filename unknown>:0 
  at L.LT (System.String key) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.get_DisplayText () [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.ToString () [0x00000] in <filename unknown>:0 
  at DeckTracker.LocalizableTextTokenizer.Tokenize (DeckTracker.DwdModelWalker walker, ICycleDetector detector, System.Collections.Generic.List`1 tokens, System.Object value) [0x00000] in <filename unknown>:0

**Comment by extesy** [comment]
@VitaliyKulikov How many SQLiteException do you see in `error.log`? Do new ones appear often or it's just one from the old days? I'm just trying to figure out if there is any correlation.

**Comment by VitaliyKulikov** [comment]
@extesy i have 4 new. seems, those exceptions happen once or two per run. i always restart then i see such behaviour. add timestamp, so we will see for sure.

**Comment by extesy** [comment]
Should be fixed now in `1.0.60`.

**Comment by VitaliyKulikov** [comment]
@extesy now game have small freezes on every draw (manipulating with deck list). no logging in `error.log` at all.

**Comment by extesy** [comment]
Your computer is probably not fast enough. Do micro-freezes happen only while drawing cards?

**Comment by extesy** [comment]
@VitaliyKulikov I actually have several questions that would help me localize the hot paths:
1. Do micro-freezes happen only while drawing cards?
2. If not, then what are all situations when it happens?
3. Do micro-freezes still happen when you hide the deck list?

**Comment by VitaliyKulikov** [comment]
so, after some testing .. it's definitely performance-degradation last patch.
* without tracker - game runs smoothly
* here notes
1. not
2. then cards attacks, abilities activated (animation freezes sometimes), even then you cast cards ( it's strange)
3. hiding overlay not helping .. behaviour same. only, running game alone helps.

**Comment by VitaliyKulikov** [comment]
maybe it's related to my system: Windows 10 Pro 64-bit
can, you build x64?

**Comment by extesy** [comment]
I think your computer might be just too slow. Unity application is a 32-bit process and there won't be any performance improvement in 64-bit mode anyways. Try latest version `1.0.61` because I've made some improvements there.

**Comment by VitaliyKulikov** [comment]
man, as i said performance-degradation. before, i hadn't any issues like that (<1.0.59).
yep, i have tried `1.0.61` - same ((. without `tracker` game works well. 

maybe, new build is related only for my configuration. i will try to investigate.
recently, also new NVidia drivers have been updated. ... maybe i am overheated during game + tracker.

my system:
```
Summary
		Operating System
			Windows 10 Pro 64-bit
		CPU
			Intel Core i7 2670QM @ 2.20GHz	
			Sandy Bridge 32nm Technology
		RAM
			6.00GB Dual-Channel DDR3 @ 664MHz (9-9-9-24)
		Motherboard
			Dell Inc. 0VP036 (CPU)	
		Graphics
			Generic PnP Monitor (1600x900@60Hz)
			Intel (Dell)
			1023MB NVIDIA GeForce GT 525M (Dell)	
			ForceWare version: 384.94
			SLI Disabled
		Storage
			698GB Seagate ST9750420AS (SATA)	
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek High Definition Audio

**Comment by extesy** [comment]
Theoretically performance degradation is possible because previously different threads were used for extra stuff and that's what caused SqliteExceptions and random in-game bugs. Now it all happens in the main Unity thread. But there's very little going on, so it shouldn't have been noticeable...

**Comment by VitaliyKulikov** [comment]
i have put graphics settings to low an even try to run on Intel graphics.
so, freezes only with `tracker` 

btw: i have found new type of exceptions: 
```
Exception happened while attaching to mono thread
Exception happened while invoking DeckTracker.InGame.dll

**Comment by VitaliyKulikov** [comment]
https://www.twitch.tv/iamcvh have same issues

**Comment by extesy** [comment]
Let's switch to #21.

**Comment by extesy** [comment]
I think I know what's going on but this issue has nothing to do with the performance problem.

**Comment by VitaliyKulikov** [comment]
sure, np. it is just from user view. from technical i know the possible reasons.
